export const queryPage=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><title>飞书只读查询</title><main><p class="eyebrow">PRIVATE · READ ONLY</p><h1>飞书只读查询</h1><p>自动选择同一账户下有权限的应用。所有操作仅读取数据。</p><a href="/">管理连接</a><form id="query-form"><label for="operation">查询内容</label><select id="operation"></select><div id="fields"></div><button type="submit">查询</button></form><p id="summary" role="status"></p><button id="next" hidden>读取下一页</button><pre id="output"></pre></main><script src="/query.js" defer></script></html>`;
export const queryScript=`const ops={search_files:['搜索云文档',['query','file_type']],wiki_spaces:['知识空间列表',[]],wiki_nodes:['知识空间中的页面',['space_id','parent_node_token']],wiki_node:['知识库页面信息',['token']],sheet_tabs:['电子表格工作表',['token']],sheet_values:['电子表格单元格',['token','range']],base_tables:['多维表格数据表',['token']],base_fields:['多维表格字段',['token','table_id']],base_records:['多维表格记录',['token','table_id']],tasks:['我负责的任务',[]],task:['任务详情',['task_guid']],tasklists:['任务清单',[]],tasklist_tasks:['清单中的任务',['tasklist_guid']],docx_text:['文档正文',['token']]};
const labels={query:'关键词',file_type:'文件类型（doc / sheet / bitable，可留空）',space_id:'知识空间 ID',parent_node_token:'父页面标识（可留空）',token:'资源链接或标识',range:'读取范围（例如 工作表ID!A1:D20）',table_id:'数据表 ID',task_guid:'任务 ID',tasklist_guid:'任务清单 ID'};
const select=document.querySelector('#operation'),fields=document.querySelector('#fields'),out=document.querySelector('#output'),summary=document.querySelector('#summary'),next=document.querySelector('#next');let cursor=null,connection=null,current=null,busy=false;
for(const [value,[label]] of Object.entries(ops)){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o);}
function render(){fields.replaceChildren();for(const key of ops[select.value][1]){const l=document.createElement('label'),i=document.createElement('input');l.htmlFor=key;l.textContent=labels[key];i.id=key;i.name=key;i.autocomplete='off';fields.append(l,i,document.createElement('br'));}cursor=null;next.hidden=true;}
select.addEventListener('change',render);render();
async function run(more=false){if(busy)return;busy=true;summary.textContent='正在读取…';try{if(!more){const parameters={};for(const key of ops[select.value][1]){let value=document.getElementById(key).value.trim();if(key==='token'&&value.startsWith('https://'))value=new URL(value).pathname.split('/').filter(Boolean).pop();if(value)parameters[key]=value;}current={operation:select.value,parameters};cursor=null;connection=null;}
 const r=await fetch('/api/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...current,...(cursor?{cursor,connection_id:connection}:{})})});const d=await r.json();if(!r.ok||d.error){summary.textContent='查询未完成：'+(d.error||r.status);out.textContent=JSON.stringify(d,null,2);next.hidden=true;return;}cursor=d.next_cursor;connection=d.connection_id;summary.textContent=(d.partial?'本页已读取，仍有更多内容':'本次查询已完成')+' · 连接：'+connection;next.hidden=!cursor;out.textContent=JSON.stringify(d.data,null,2);
 }catch(e){summary.textContent='读取失败，请检查连接后重试';}finally{busy=false;}}
document.querySelector('#query-form').addEventListener('submit',e=>{e.preventDefault();run();});next.addEventListener('click',()=>run(true));`;
