export const queryPage=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/query.css"><title>飞书通用只读查询</title><main><p class="eyebrow">PRIVATE · READ ONLY</p><h1>飞书通用只读查询</h1><p>自动选择同一账户下有权限的应用。所有操作仅读取数据。</p><a href="/">管理连接</a><form id="query-form"><label for="operation">查询内容</label><select id="operation"></select><div id="fields"></div><button type="submit">查询</button></form><p id="summary" role="status"></p><button id="next" hidden>读取下一页</button><section id="results" aria-label="查询结果"></section><details><summary>查看原始数据</summary><pre id="output"></pre></details></main><script src="/query.js" defer></script></html>`;
export const queryScript=`const ops={search_files:['搜索云文档',['query','file_type']],wiki_spaces:['知识空间列表',[]],wiki_nodes:['知识空间中的页面',['space_id','parent_node_token']],wiki_node:['知识库页面信息',['token']],sheet_tabs:['电子表格工作表',['token']],sheet_values:['电子表格单元格',['token','range']],base_tables:['多维表格数据表',['token']],base_fields:['多维表格字段',['token','table_id']],base_records:['多维表格记录',['token','table_id']],tasks:['我负责的任务',[]],task:['任务详情',['task_guid']],tasklists:['任务清单',[]],tasklist_tasks:['清单中的任务',['tasklist_guid']],docx_text:['文档正文',['token']]};
const labels={query:'关键词',file_type:'文件类型（doc / sheet / bitable，可留空）',space_id:'知识空间 ID',parent_node_token:'父页面标识（可留空）',token:'资源链接或标识',range:'读取范围（例如 工作表ID!A1:D20）',table_id:'数据表 ID',task_guid:'任务 ID',tasklist_guid:'任务清单 ID'};
const select=document.querySelector('#operation'),fields=document.querySelector('#fields'),out=document.querySelector('#output'),summary=document.querySelector('#summary'),next=document.querySelector('#next');let cursor=null,connection=null,current=null,busy=false,loaded=0;const results=document.querySelector("#results");
for(const [value,[label]] of Object.entries(ops)){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o);}
function render(){fields.replaceChildren();for(const key of ops[select.value][1]){const l=document.createElement('label'),i=document.createElement('input');l.htmlFor=key;l.textContent=labels[key];i.id=key;i.name=key;i.autocomplete='off';fields.append(l,i,document.createElement('br'));}cursor=null;next.hidden=true;results.replaceChildren();summary.textContent='';out.textContent='';}
select.addEventListener('change',render);render();
async function run(more=false){if(busy)return;busy=true;summary.textContent='正在读取…';document.querySelectorAll('button,select,input').forEach(x=>x.disabled=true);try{if(!more){const parameters={};for(const key of ops[select.value][1]){let value=document.getElementById(key).value.trim();if(key==='token'&&value.startsWith('https://'))value=new URL(value).pathname.split('/').filter(Boolean).pop();if(value)parameters[key]=value;}current={operation:select.value,parameters};cursor=null;connection=null;loaded=0;results.replaceChildren();out.textContent="";}
 const r=await fetch('/api/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...current,...(cursor?{cursor,connection_id:connection}:{})})});const d=await r.json();if(!r.ok||d.error){summary.textContent='查询未完成：'+(d.error||r.status);out.textContent=JSON.stringify(d,null,2);next.hidden=true;return;}cursor=d.next_cursor;connection=d.connection_id;const n=show(d.data,current.operation,more);loaded+=n;summary.textContent=(cursor?'已读取 '+loaded+' 项，仍有更多内容':d.partial?'已读取 '+loaded+' 项；服务返回部分结果，不能继续翻页':'读取完成 · '+loaded+' 项')+' · 应用：'+connection;next.hidden=!cursor;out.textContent=JSON.stringify(d.data,null,2);
 }catch(e){summary.textContent='读取失败，请检查连接后重试';}finally{busy=false;document.querySelectorAll('button,select,input').forEach(x=>x.disabled=false);}}

function el(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n;}
function value(x){if(x==null)return '—';if(Array.isArray(x))return x.map(value).join('、');if(typeof x==='object')return x.text||x.name||x.title||x.link||x.url||JSON.stringify(x);return String(x);}
function link(parent,url,label='打开飞书来源'){try{const u=new URL(url);if(u.protocol!=='https:'||!(u.hostname==='feishu.cn'||u.hostname.endsWith('.feishu.cn')||u.hostname==='larksuite.com'||u.hostname.endsWith('.larksuite.com')))return;const a=el('a',label,parent);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';}catch{}}
function table(headers,rows){const t=el('table',undefined,results),thead=el('thead',undefined,t),tr=el('tr',undefined,thead);headers.forEach(h=>el('th',h,tr));const body=el('tbody',undefined,t);rows.forEach(row=>{const r=el('tr',undefined,body);row.forEach(c=>el('td',value(c),r));});}
function show(data,op,more){if(!more)results.replaceChildren();
 if(op==='docx_text'){el('pre',data.content||'',results);return data.content?1:0;}
 if(op==='sheet_values'){const v=data.valueRange||data.value_range||{};const rows=v.values||data.values||[];el('p',v.range||current.parameters.range,results);if(rows.length)table(Array.from({length:Math.max(...rows.map(x=>x.length))},(_,i)=>'第 '+(i+1)+' 列'),rows);else el('p','此范围没有数据',results);return rows.length;}
 const items=data.items||data.docs_entities||data.sheets||(data.task?[data.task]:data.node?[data.node]:[]);
 if(!items.length){el('p','没有可显示的记录',results);return 0;}
 if(op==='base_records'){const headers=[...new Set(items.flatMap(x=>Object.keys(x.fields||{})))];if(headers.length)table(headers,items.map(x=>headers.map(h=>(x.fields||{})[h])));else el('p','本页记录的字段为空',results);return items.length;}
 if(op==='base_fields'){table(['字段名称','字段类型'],items.map(x=>[x.field_name,x.ui_type||x.type]));return items.length;}
 for(const x of items){const c=el('article',undefined,results);c.className='result-card';el('h2',x.summary||x.title||x.name||'未命名',c);
 if(op==='tasks'||op==='task'||op==='tasklist_tasks'){el('p',x.status==='done'||(x.completed_at&&x.completed_at!=='0')?'已完成':'待办',c).className='badge';if(x.description)el('p',x.description,c);if(x.due?.timestamp){const date=new Date(Number(x.due.timestamp));if(!isNaN(date))el('p','截止：'+date.toLocaleString('zh-CN'),c);}}
 else {if(x.description)el('p',x.description,c);const kind=x.obj_type||x.docs_type;if(kind)el('p','类型：'+kind,c).className='badge';const id=x.space_id||x.sheet_id||x.table_id||x.guid||x.node_token||x.docs_token;if(id)el('p','标识：'+id,c).className='badge';}
 if(x.url)link(c,x.url);
 }return items.length;
}
document.querySelector('#query-form').addEventListener('submit',e=>{e.preventDefault();run();});next.addEventListener('click',()=>run(true));`;

export const queryStyle=`main{max-width:1100px;margin:auto;padding:24px}#results{overflow:auto;margin:24px 0}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:12px;text-align:left;border-bottom:1px solid #dce1e5;vertical-align:top;white-space:pre-wrap;min-width:100px;max-width:360px;overflow-wrap:anywhere}th{background:#f3f5f7}.result-card{border:1px solid #dce1e5;border-radius:12px;padding:18px;margin:12px 0}.result-card h2{font-size:18px;margin:0 0 10px}.result-card p{white-space:pre-wrap;overflow-wrap:anywhere}.badge{color:#536577;font-size:13px}pre{white-space:pre-wrap;overflow-wrap:anywhere}details{margin-top:24px}button:disabled{opacity:.5}#summary{white-space:pre-wrap}input,select{max-width:100%;box-sizing:border-box}@media(max-width:600px){main{padding:14px}th,td{padding:8px}}`;
