import { beforeAll,beforeEach,afterAll,describe,it,expect,vi } from 'vitest';
import { readFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import { request as httpRequest, type Server } from 'node:http';
import { createAgendaServer } from '../apps/mcp-server/src/agenda-server.js';
import { PostgresResourceAccess,AGENDA_PROVIDER_SCOPES,GrantedAgendaTokens } from '../packages/auth/src/resource-access.js';
import { PostgresConnectionRepository } from '../packages/auth/src/connection-repository.js';
import { PostgresTokenStore,TokenCipher } from '../packages/auth/src/vault.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { digest,Handles } from '../packages/policy/src/core.js';

async function localFetch(url:string,options:{method?:string;headers?:Record<string,string>;body?:string}={}){return new Promise<{status:number;headers:Headers;json:()=>Promise<any>}>((resolve,reject)=>{const req=httpRequest(url,{method:options.method??'GET',headers:options.headers},res=>{const chunks:Buffer[]=[];res.on('data',(chunk:Buffer)=>chunks.push(chunk));res.on('end',()=>{const headers=new Headers();for(const [key,value]of Object.entries(res.headers))if(value!==undefined)headers.set(key,Array.isArray(value)?value.join(','):value);resolve({status:res.statusCode!,headers,json:async()=>JSON.parse(Buffer.concat(chunks).toString())});});});req.on('error',reject);req.end(options.body);});}
const resource='https://mcp.example.test/mcp';const issuer='https://identity.example.test/';const bearer='A'.repeat(43);
const identity={...demoIdentity(),scopes:['calendar.read']};const args={time_range:{start:'2026-10-05T00:00:00Z',end:'2026-10-06T00:00:00Z'},timezone:'UTC'};
const tokenData={accessToken:'synthetic-feishu-user-access',refreshToken:'synthetic-feishu-refresh',expiresAt:Date.now()+3600000,refreshExpiresAt:Date.now()+86400000};
const instances=[{event_id:'recurring_1',summary:'Occurrence 1',start_time:{timestamp:'1791190800'},end_time:{timestamp:'1791194400'},status:'confirmed'},{event_id:'recurring_2',summary:'Occurrence 2',start_time:{timestamp:'1791198000'},end_time:{timestamp:'1791201600'},status:'confirmed'}];
let db:PGlite,server:Server,base:string;const provider=vi.fn();
const query=async(sql:string,values?:unknown[])=>{const result=await db.query(sql,values);return{...result,rowCount:result.affectedRows??result.rows.length};};
const cipher=new TokenCipher(new Map([['fixture',randomBytes(32)]]),'fixture');
const repository=new PostgresConnectionRepository({connect:async()=>({query,release:()=>{}})} as never,cipher);
const access=new PostgresResourceAccess({query} as never);const tokens=new PostgresTokenStore({query} as never,cipher);
async function grant(token=bearer,subject=identity.subject,connection=identity.connectionId,generation='1',audience=resource){const grantId='g_'+digest(token).slice(0,12);await query('INSERT INTO oauth_grants(id,subject,connection_id,scopes,resource) VALUES($1,$2,$3,$4,$5)',[grantId,subject,connection,['calendar.read'],audience]);await query("INSERT INTO mcp_access_tokens(token_hash,grant_id,grant_generation,expires_at) VALUES($1,$2,$3,now()+interval '1 hour')",[digest(token),grantId,generation]);}
async function request(method:string,params:unknown={},token:string|null=bearer,overrides:Record<string,string>={}){const response=await localFetch(base+'/mcp',{method:'POST',headers:{Host:'mcp.example.test','Content-Type':'application/json',Accept:'application/json, text/event-stream',...(token?{Authorization:'Bearer '+token}:{}),...overrides},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});return{status:response.status,headers:response.headers,body:await response.json() as any};}
beforeAll(async()=>{db=await PGlite.create();for(const file of ['001_connections.sql','002_oauth_link_attempts.sql','003_resource_access.sql'])await db.exec(await readFile(new URL('../infra/migrations/'+file,import.meta.url),'utf8'));server=createAgendaServer({resource,authorizationServer:issuer,access,tokens,handles:new Handles(randomBytes(32)),client:()=>createSafeSdkClient({appId:'fixture-app',appSecret:'synthetic-app-secret',domain:'feishu',httpInstance:{request:provider} as never})});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+(server.address() as {port:number}).port;},30000);
beforeEach(async()=>{await db.exec('TRUNCATE feishu_connections CASCADE');provider.mockReset();provider.mockImplementation(async config=>config.url.endsWith('/calendars')?{code:0,data:{calendar_list:[{calendar_id:'calendar1'}],has_more:false}}:{code:0,data:{items:instances}});await repository.link(identity,{openId:'ou_fixture',tenantId:identity.tenantId,grantedProviderScopes:AGENDA_PROVIDER_SCOPES},tokenData);await grant();});
afterAll(async()=>{await new Promise<void>(resolve=>{server.close(()=>resolve());server.closeAllConnections();});await db.close();});
describe('HTTP bearer -> durable grant -> provider router -> agenda instances',()=>{
  it('keeps same-tenant accounts and agenda references isolated through HTTP',async()=>{const beta={...demoIdentity('beta'),scopes:['calendar.read']};await repository.link(beta,{openId:'ou_beta',tenantId:beta.tenantId,grantedProviderScopes:AGENDA_PROVIDER_SCOPES},{...tokenData,accessToken:'synthetic-beta-user-access'});await grant('B'.repeat(43),beta.subject,beta.connectionId);const alpha=await request('tools/call',{name:'get_agenda',arguments:{...args,page_size:1}});const cursor=alpha.body.result.structuredContent.meta.next_cursor;const calls=provider.mock.calls.length;const replay=await request('tools/call',{name:'get_agenda',arguments:{...args,page_size:1,cursor}},'B'.repeat(43));expect(replay.body.result.structuredContent.error.type).toBe('PERMISSION_DENIED');expect(provider).toHaveBeenCalledTimes(calls);const own=await request('tools/call',{name:'get_agenda',arguments:args},'B'.repeat(43));expect(own.body.result.structuredContent.ok).toBe(true);expect(provider.mock.calls.at(-1)![0].headers.Authorization==='Bearer synthetic-beta-user-access').toBe(true)});
  it('rejects duplicate authorization fields before querying provider data',async()=>{const status=await new Promise<number>((resolve,reject)=>{const req=httpRequest(base+'/mcp',{method:'POST',headers:['Host','mcp.example.test','Content-Type','application/json','Authorization','Bearer '+bearer,'Authorization','Bearer '+'B'.repeat(43)]},res=>{res.resume();res.on('end',()=>resolve(res.statusCode!));});req.on('error',reject);req.end(JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'}));});expect(status).toBe(401);expect(provider).not.toHaveBeenCalled()});
  it('enforces the streamed body limit when content length is absent',async()=>{const status=await new Promise<number>((resolve,reject)=>{const req=httpRequest(base+'/mcp',{method:'POST',headers:{Host:'mcp.example.test','Content-Type':'application/json',Authorization:'Bearer '+bearer}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode!));});req.on('error',reject);req.write('x'.repeat(33000));req.end('x'.repeat(33000));});expect(status).toBe(413);expect(provider).not.toHaveBeenCalled()});
  it('discovers only the single approved read tool',async()=>{const result=await request('tools/list');expect(result.status).toBe(200);expect(result.body.result.tools.map((tool:any)=>tool.name)).toEqual(['get_agenda']);expect(provider).not.toHaveBeenCalled()});
  it('reads recurring instances through the real SDK with a Feishu user token, never the MCP bearer',async()=>{const result=await request('tools/call',{name:'get_agenda',arguments:args});expect(result.status).toBe(200);expect(result.body.result.structuredContent.ok).toBe(true);expect(result.body.result.structuredContent.data.events.map((event:any)=>event.event_id)).toEqual(['recurring_1','recurring_2']);expect(result.body.result.structuredContent.meta).toMatchObject({source:'feishu_api',live_verified:false});expect(provider.mock.calls[1]![0].url).toBe('https://open.feishu.cn/open-apis/calendar/v4/calendars/calendar1/events/instance_view');expect(provider.mock.calls.every(call=>call[0].headers.Authorization==='Bearer '+tokenData.accessToken)).toBe(true);expect(provider.mock.calls.every(call=>!JSON.stringify(call).includes(bearer))).toBe(true);expect(provider.mock.calls[1]![0].params).not.toHaveProperty('page_token')});
  it('continues a stable locally paged instance view through another authenticated HTTP request',async()=>{const first=await request('tools/call',{name:'get_agenda',arguments:{...args,page_size:1}});const cursor=first.body.result.structuredContent.meta.next_cursor;expect(cursor).toBeTruthy();const second=await request('tools/call',{name:'get_agenda',arguments:{...args,page_size:1,cursor}});expect(second.body.result.structuredContent.data.events[0].event_id).toBe('recurring_2');expect(second.body.result.structuredContent.meta.next_cursor).toBeNull();expect(provider.mock.calls.filter(call=>call[0].url.endsWith('/calendars'))).toHaveLength(1)});
  it.each(['B'.repeat(43),'short','token.with.jwt.shape'])('rejects unknown/invalid bearer before any provider request',async token=>{expect((await request('tools/list',{},token)).status).toBe(401);expect(provider).not.toHaveBeenCalled()});
  it('rejects a missing bearer with resource metadata discovery',async()=>{const result=await request('tools/list',{},null);expect(result.status).toBe(401);expect(result.headers.get('www-authenticate')).toContain('/.well-known/oauth-protected-resource/mcp');expect(provider).not.toHaveBeenCalled()});
  it('publishes resource metadata without pretending to implement an authorization issuer',async()=>{const response=await localFetch(base+'/.well-known/oauth-protected-resource/mcp',{headers:{Host:'mcp.example.test'}});expect(await response.json()).toEqual({resource,authorization_servers:[issuer],scopes_supported:['calendar.read'],bearer_methods_supported:['header']});const forbidden=await localFetch(base+'/oauth/authorize',{headers:{Host:'mcp.example.test'}});expect(forbidden.status).toBe(404)});
  it.each(["UPDATE mcp_access_tokens SET expires_at=now()-interval '1 second'","UPDATE mcp_access_tokens SET revoked_at=now()","UPDATE oauth_grants SET revoked_at=now()","UPDATE oauth_grants SET resource='https://other.example.test/mcp'","UPDATE oauth_grants SET subject='someone-else'","UPDATE feishu_connections SET status='revoked'","UPDATE feishu_connections SET scopes=ARRAY[]::text[]"])('refuses invalid persisted authorization',async sql=>{await db.exec(sql);expect((await request('tools/list')).status).toBe(401);expect(provider).not.toHaveBeenCalled()});
  it('rejects same-ID relink ABA and only accepts newly issued generation-bound access',async()=>{await repository.link(identity,{openId:'ou_fixture',tenantId:identity.tenantId,grantedProviderScopes:AGENDA_PROVIDER_SCOPES},{...tokenData,accessToken:'synthetic-new-token'});expect((await request('tools/list')).status).toBe(401);await grant('N'.repeat(43),identity.subject,identity.connectionId,'2');expect((await request('tools/list',{},'N'.repeat(43))).status).toBe(200)});
  it.each([{scopes:[]},{scopes:['calendar.read']},{scopes:['calendar:calendar:read']}])('does not substitute internal scopes or partial provider consent',async({scopes})=>{await query('UPDATE feishu_connections SET provider_scopes=$1',[scopes]);expect((await request('tools/list')).status).toBe(403);expect(provider).not.toHaveBeenCalled()});
  it('stores only the MCP token hash and encrypted Feishu credentials',async()=>{const rows=await query('SELECT t.token_hash,f.sealed FROM mcp_access_tokens t CROSS JOIN feishu_tokens f');const serialized=JSON.stringify(rows.rows);expect(serialized.includes(bearer)).toBe(false);expect(serialized.includes(tokenData.accessToken)).toBe(false)});
  it('stops before the second provider call if the account is disconnected during traversal',async()=>{provider.mockImplementationOnce(async()=>{await repository.disconnect(identity);return{code:0,data:{calendar_list:[{calendar_id:'calendar1'}],has_more:false}};});const result=await request('tools/call',{name:'get_agenda',arguments:args});expect(result.body.result.structuredContent.error.type).toBe('AUTH_REQUIRED');expect(result.body.result.structuredContent.data).toBeUndefined();expect(provider).toHaveBeenCalledTimes(1)});
  it('does not disguise a lost actual provider grant as a partial calendar-specific 403',async()=>{provider.mockImplementationOnce(async()=>{await db.exec("UPDATE feishu_connections SET provider_scopes='{}'");return{code:0,data:{calendar_list:[{calendar_id:'calendar1'}],has_more:false}};});const result=await request('tools/call',{name:'get_agenda',arguments:args});expect(result.body.result.structuredContent.ok).toBe(false);expect(result.body.result.structuredContent.error.type).toBe('AUTH_REQUIRED');expect(provider).toHaveBeenCalledTimes(1)});
  it('requires a current Feishu token and does not refresh or obtain a bot token implicitly',async()=>{await tokens.put(identity,{...tokenData,expiresAt:0});const result=await request('tools/call',{name:'get_agenda',arguments:args});expect(result.body.result.structuredContent.error.type).toBe('AUTH_REQUIRED');expect(provider).not.toHaveBeenCalled()});
  it('cannot select another identity or another tool in model arguments',async()=>{const malicious=await request('tools/call',{name:'get_agenda',arguments:{...args,subject:'other'}});expect(malicious.body.error??malicious.body.result?.isError).toBeTruthy();for(const name of ['get_profile','create_event','request']){const result=await request('tools/call',{name,arguments:{}});expect(result.body.error??result.body.result?.isError).toBeTruthy();}expect(provider).not.toHaveBeenCalled()});
  it('rejects hostile Host/Origin and bearer query transport',async()=>{expect((await request('tools/list',{},bearer,{Host:'attacker.example.test'})).status).toBe(403);expect((await request('tools/list',{},bearer,{Origin:'https://attacker.example.test'})).status).toBe(403);const queryToken=await localFetch(base+'/mcp?access_token='+bearer,{method:'POST',headers:{Host:'mcp.example.test'}});expect(queryToken.status).toBe(400);expect(provider).not.toHaveBeenCalled()});
  it('rejects oversized bodies and misleading JSON media types',async()=>{const oversized=await localFetch(base+'/mcp',{method:'POST',headers:{Host:'mcp.example.test',Authorization:'Bearer '+bearer,'Content-Type':'application/json'},body:'x'.repeat(65537)});expect(oversized.status).toBe(413);expect((await request('tools/list',{},bearer,{'Content-Type':'application/jsonp'})).status).toBe(415);expect(provider).not.toHaveBeenCalled()});
  it('sanitizes database failures without rendering a driver message',async()=>{const failing=new PostgresResourceAccess({query:vi.fn().mockRejectedValue(new Error('secret-dsn-value'))} as never);await expect(failing.authenticate(bearer,resource)).rejects.toThrow('storage is unavailable')});
  it('checks token snapshot generation and caller identity independently of the first lookup',async()=>{const original=await access.authenticate(bearer,resource);const guarded=new GrantedAgendaTokens(access,{snapshot:async()=>({revision:'2:1',tokens:tokenData})},bearer,original);await expect(guarded.get(identity)).rejects.toThrow('changed');await expect(guarded.get({...identity,subject:'other'})).rejects.toThrow('changed')});
});
