import { describe,it,expect,vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { FeishuInstanceAgenda } from '../packages/feishu/src/provider-instance-agenda.js';
import { FeishuSdkReadGateway,bindSdkReads } from '../packages/feishu/src/sdk-reads.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';
const input={calendar_id:'calendar1',time_range:{start:'2026-10-05T00:00:00Z',end:'2026-10-06T00:00:00Z'},timezone:'UTC'};
const event={event_id:'event_1',summary:'Fixture',start_time:{date:'2026-10-05'},end_time:{date:'2026-10-06'},status:'confirmed'};
function setup(){const request=vi.fn();const identity=demoIdentity();const client=createSafeSdkClient({appId:'fixture',appSecret:'fixture',domain:'feishu',httpInstance:{request} as never});const gateway=new FeishuSdkReadGateway({identity,reads:bindSdkReads(client)},{get:async()=>({accessToken:'synthetic-user',refreshToken:'synthetic-refresh',expiresAt:Date.now()+1e6,refreshExpiresAt:Date.now()+2e6})});return{identity,request,agenda:new FeishuInstanceAgenda(gateway,new Handles(randomBytes(32)))}};
describe('real agenda instance contract',()=>{
  it('never discards an unexpected provider continuation marker',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[event],has_more:true,page_token:'unexpected'}});await expect(s.agenda.agenda(s.identity,input)).rejects.toThrow('pagination')});
  it('preserves all-day dates and excludes explicit cancellations and out-of-window events',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[event,{event_id:'cancelled',status:'cancelled'},{...event,event_id:'outside',start_time:{date:'2026-10-07'},end_time:{date:'2026-10-08'}}]}});const result=await s.agenda.agenda(s.identity,input);expect(result.events).toHaveLength(1);expect(result.events[0]!.start).toEqual({date:'2026-10-05'});expect(s.request.mock.calls[0]![0]).toMatchObject({method:'GET',params:{start_time:'1791158400',end_time:'1791244800',user_id_type:'open_id'}});expect(s.request.mock.calls[0]![0].params).not.toHaveProperty('page_size')});
  it.each([{}, {items:null},{items:Array.from({length:201},()=>event)}])('fails absent or oversized provider views',async data=>{const s=setup();s.request.mockResolvedValue({code:0,data});await expect(s.agenda.agenda(s.identity,input)).rejects.toThrow('200-item')});
  it.each([{...event,start_time:{}},{...event,start_time:{date:'2026-02-30'}},{...event,start_time:{timestamp:'not-a-time'}},{...event,start_time:{date:'2026-10-05',timestamp:'1791158400'}},{...event,end_time:{date:'2026-10-04'}},{...event,status:'unknown'}])('rejects unknown/contradictory instance timing',async value=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[value]}});await expect(s.agenda.agenda(s.identity,input)).rejects.toThrow('malformed')});
  it('rejects repeated occurrence IDs rather than duplicating events',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[event,event]}});await expect(s.agenda.agenda(s.identity,input)).rejects.toThrow('repeated')});
  it('invalidates local continuation when the instance view changes',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[event,{...event,event_id:'event_2'}]}}).mockResolvedValueOnce({code:0,data:{items:[{...event,summary:'changed'},{...event,event_id:'event_2'}]}});const first=await s.agenda.agenda(s.identity,input,{page_size:1});await expect(s.agenda.agenda(s.identity,input,{page_size:1,cursor:first.next_cursor!})).rejects.toThrow('Cursor')});
  it('rejects an excessive window before provider transport',async()=>{const s=setup();await expect(s.agenda.agenda(s.identity,{...input,time_range:{start:input.time_range.start,end:'2026-12-01T00:00:00Z'}})).rejects.toThrow('31 days');expect(s.request).not.toHaveBeenCalled()});
});
