import { beforeAll,beforeEach,afterAll,describe,it,expect,vi } from 'vitest';
import { request as httpRequest } from 'node:http';
import { createReviewFixture,localRequest,input,bearer,created,reviewOrigin,tokenData,identity } from './helpers/document-review-fixture.js';
let f:Awaited<ReturnType<typeof createReviewFixture>>;const transport=vi.fn();
beforeAll(async()=>{f=await createReviewFixture(transport);},30000);
beforeEach(async()=>{await f.reset();transport.mockReset();transport.mockResolvedValue(created);});
afterAll(async()=>{await f.close();});
describe('trusted browser review → explicit confirmation → durable create receipt',()=>{
 it('renders the full target/content and verified account without executing or leaking bearer/proof',async()=>{const s=await f.open();expect(s.status).toBe(200);expect(s.data.input).toEqual(input);expect(s.text).toContain('ou_synthetic');expect(s.text).toContain('fld_fixture');expect(s.text).toContain('Synthetic document &amp; &lt;title&gt;');for(const secret of [bearer,tokenData.accessToken,'PRIVATE KEY'])expect(s.text).not.toContain(secret);expect(s.headers.get('set-cookie')).toMatch(/__Host-.*; Path=\/; Secure; HttpOnly; SameSite=Strict/);expect(s.headers.get('cache-control')).toBe('no-store');expect(s.headers.get('referrer-policy')).toBe('no-referrer');expect(s.headers.get('content-security-policy')).toContain("frame-ancestors 'none'");expect(transport).not.toHaveBeenCalled();});
 it('creates only after the current cookie + CSRF + exact content confirmation, then replays only receipt',async()=>{const s=await f.open();expect((await f.act(s,'status')).json.can_submit).toBe(true);expect(transport).not.toHaveBeenCalled();const a=await f.act(s,'confirm',{input});expect(a.status).toBe(200);expect(a.json.receipt.status).toBe('succeeded');expect((await f.act(s,'confirm',{input})).json.receipt.status).toBe('succeeded');expect(transport).toHaveBeenCalledTimes(1);expect(transport.mock.calls[0]![0].headers.Authorization).toBe('Bearer '+tokenData.accessToken);});
 it('stores hashes and token-row references only, never body, bearer, cookies or csrf',async()=>{const s=await f.open();const rows=JSON.stringify((await f.query('SELECT * FROM document_review_sessions')).rows);for(const value of [input.title,input.markdown,bearer,s.cookie!.split('=')[1]!,s.fields.csrf,tokenData.accessToken])expect(rows).not.toContain(value);});
 it('requires independent host attestation even when a valid MCP bearer and Origin are supplied',async()=>{const p=await f.w.preview(bearer,input,'missing_handoff');const r=await localRequest(f.base,'/document-review',{version:1,intent_id:p.receipt.intent_id,input},{Authorization:'Bearer '+bearer});expect(r.status).toBe(400);expect(transport).not.toHaveBeenCalled();});
 it.each(['true','bad.signature','', 'a.b.c'])('rejects forged handoff %s',async proof=>{const s=await f.open(undefined,input,{'x-document-review-handoff':proof});expect(s.status).toBeGreaterThanOrEqual(400);expect(transport).not.toHaveBeenCalled();});
 it.each([{origin:'https://other.example.test'},{binding:'a'.repeat(64)},{request:'b'.repeat(64)},{intent:'00000000-0000-4000-8000-000000000000'},{version:2},{purpose:'approve'},{expires:1},{issued:Date.now()+600000,expires:Date.now()+660000},{expires:Date.now()+600000},{approved:true}])('binds handoff claims and lifetime %j',async patch=>{const p=await f.w.preview(bearer,input,'handoff_claim');const r=await f.open(p,input,{'x-document-review-handoff':f.proof(p,patch)});expect(r.status).toBeGreaterThanOrEqual(400);expect(transport).not.toHaveBeenCalled();});
 it('consumes the host nonce once, even for repeated bootstrap requests',async()=>{const p=await f.w.preview(bearer,input,'nonce_fixture');const proof=f.proof(p);expect((await f.open(p,input,{'x-document-review-handoff':proof})).status).toBe(200);expect((await f.open(p,input,{'x-document-review-handoff':proof})).status).toBe(401);expect((await f.query('SELECT * FROM document_review_sessions')).rows).toHaveLength(1);});
 it.each([['Origin',null],['Origin','null'],['Origin','https://other.example.test'],['Host','other.example.test']])('rejects noncanonical browser origin/host %s %s',async(name,value)=>{const s=await f.open(undefined,input,{[name!]:value});expect(s.status).toBe(403);});
 it.each(['Origin','Host','Authorization','x-document-review-handoff'])('rejects duplicate %s headers',async name=>{const p=await f.w.preview(bearer,input,'duplicate');const h=['Host','review.example.test','Origin',reviewOrigin,'Authorization','Bearer '+bearer,'x-document-review-handoff',f.proof(p),'Content-Type','application/json'];h.push(name,h[h.findIndex(v=>v.toLowerCase()===name.toLowerCase())+1]!);const status=await new Promise<number>((resolve,reject)=>{const r=httpRequest(f.base+'/document-review',{method:'POST',headers:h},res=>{res.resume();res.on('end',()=>resolve(res.statusCode!));});r.on('error',reject);r.end(JSON.stringify({version:1,intent_id:p.receipt.intent_id,input}));});expect(status).toBe(400);});
 it.each([{confirmed:true},{approved:true},{version:2},{request_hash:'a'.repeat(64)},{csrf:'B'.repeat(43)},{intent_id:'00000000-0000-4000-8000-000000000000'}])('rejects client assertion or changed binding %j',async patch=>{const s=await f.open();expect((await f.act(s,'confirm',{input,...patch})).status).toBeGreaterThanOrEqual(400);expect(transport).not.toHaveBeenCalled();});
 it.each([{title:'Other'},{markdown:'Other'},{folder_token:'fld_other'}])('rejects content edits after preview %j',async patch=>{const s=await f.open();expect((await f.act(s,'confirm',{input:{...input,...patch}})).status).toBe(409);expect(transport).not.toHaveBeenCalled();});
 it('rejects action bearer headers and duplicate cookies, and prevents tab-cookie substitution',async()=>{const a=await f.open(),b=await f.open();expect((await f.act(a,'confirm',{input},{Authorization:'Bearer '+bearer})).status).toBe(400);expect((await f.act(a,'confirm',{input},{Cookie:a.cookie+'; '+a.cookie})).status).toBe(401);expect((await f.act(a,'confirm',{input},{Cookie:b.cookie!})).status).toBeGreaterThanOrEqual(400);expect(transport).not.toHaveBeenCalled();});
 it.each(["UPDATE document_review_sessions SET expires_at=now()-interval '1 second'","UPDATE mcp_access_tokens SET revoked_at=now()","UPDATE oauth_grants SET revoked_at=now()","UPDATE oauth_grants SET resource='https://other.example.test/mcp'","UPDATE feishu_connections SET grant_generation=grant_generation+1","UPDATE feishu_connections SET provider_scopes='{}'","UPDATE feishu_connections SET status='revoked'"])('revalidates current grant/account/session before confirm: %s',async sql=>{const s=await f.open();await f.db.exec(sql);expect((await f.act(s,'confirm',{input})).status).toBeGreaterThanOrEqual(400);expect(transport).not.toHaveBeenCalled();});
 it('cancel closes and cancels the shared intent before acknowledging, no creation on a second window',async()=>{const a=await f.open(),b=await f.open(a.preview);expect((await f.act(a,'close')).json.cancelled).toBe(true);expect((await f.act(a,'confirm',{input})).status).toBe(401);const result=await f.act(b,'confirm',{input});expect(result.json.receipt?.status??result.status).not.toBe('succeeded');expect((await f.store.get(await f.access.authenticate(bearer),a.data.intent_id)).status).toBe('cancelled');expect(transport).not.toHaveBeenCalled();});
 it('never claims cancellation after execution has started in another window',async()=>{const a=await f.open(),b=await f.open(a.preview);let release!:(x:unknown)=>void,started!:()=>void;const reached=new Promise<void>(r=>started=r);transport.mockImplementationOnce(async()=>{started();return new Promise(r=>release=r);});const creating=f.act(a,'confirm',{input});await reached;const close=await f.act(b,'close');expect(close.status).toBe(409);expect(close.json.cancelled).toBe(false);release(created);expect((await creating).json.receipt.status).toBe('succeeded');expect(transport).toHaveBeenCalledTimes(1);});
 it('concurrent clicks and two separate handoffs still perform at most one provider mutation',async()=>{const a=await f.open(),b=await f.open(a.preview);await Promise.all([f.act(a,'confirm',{input}),f.act(a,'confirm',{input}),f.act(b,'confirm',{input})]);expect(transport).toHaveBeenCalledTimes(1);});
 it('returns uncertain after a provider transport failure and never retries create on status/confirm',async()=>{transport.mockRejectedValue(new Error('synthetic provider error'));const s=await f.open();expect((await f.act(s,'confirm',{input})).json.receipt.status).toBe('uncertain');await f.act(s,'status',{refresh:true});await f.act(s,'confirm',{input});expect(transport).toHaveBeenCalledTimes(1);});
 it('reads async receipts only after submission, and never issues another POST',async()=>{const pending={code:0,data:{task:{task_id:'task_fixture',type:'create_document',status:'processing'}}};transport.mockResolvedValueOnce(pending).mockResolvedValueOnce({code:0,data:{task:{task_id:'task_fixture',type:'create_document',status:'succeeded',result:{create_document:JSON.stringify(created.data)}}}});const s=await f.open();await f.act(s,'status',{refresh:true});expect(transport).not.toHaveBeenCalled();expect((await f.act(s,'confirm',{input})).json.can_refresh).toBe(true);expect((await f.act(s,'status',{refresh:true})).json.receipt.status).toBe('succeeded');expect(transport.mock.calls.map(c=>c[0].method)).toEqual(['POST','GET']);});
 it('GET/reload never restores the sensitive preview or executes a write',async()=>{const s=await f.open();const r=await localRequest(f.base,'/document-review',undefined,{Cookie:s.cookie!},'GET');expect(r.status).toBe(200);expect(r.text).not.toContain('id="confirm"');expect(r.text).not.toContain(input.markdown);expect(transport).not.toHaveBeenCalled();});
 it('does not put secrets in URLs or allow misleading content types',async()=>{expect((await localRequest(f.base,'/document-review?token='+bearer,{})).status).toBe(400);expect((await f.open(undefined,input,{'Content-Type':'text/plain'})).status).toBe(415);expect(transport).not.toHaveBeenCalled();});
});

describe('separate disabled runtime and execution gates',()=>{
 it('default disabled server reads no storage and makes no provider request',async()=>{const disabled=await createReviewFixture(transport,{});try{const r=await localRequest(disabled.base,'/document-review',{});expect(r.status).toBe(503);expect(r.text).toContain('尚未启用');}finally{await disabled.close();}},30000);
 it('review-only permits preview/cancel but never a confirmed mutation',async()=>{const readonly=await createReviewFixture(transport,{enabled:true,allowCreate:false});try{const s=await readonly.open();expect(s.status).toBe(200);expect((await readonly.act(s,'status')).json.can_submit).toBe(false);expect((await readonly.act(s,'confirm',{input})).status).toBe(503);expect((await readonly.act(s,'close')).json.cancelled).toBe(true);expect(transport).not.toHaveBeenCalled();}finally{await readonly.close();}},30000);
});
