import { describe,it,expect,vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import { generateKeyPairSync,randomBytes } from 'node:crypto';
import { parseDocumentReviewHostPublicKey,DocumentReviewHandoffVerifier } from '../packages/auth/src/document-review-handoff.js';
const source=readFileSync(new URL('../apps/mcp-server/ui/review.js',import.meta.url),'utf8');
const ready={ok:true,phase:'review',receipt:{status:'preview'},can_submit:true,can_refresh:false,remaining_ms:60000};
const response=(value:any,ok=true)=>({ok,json:async()=>value});
const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve();};
function client(fetcher:any){
 const events:Record<string,Function>={},elements:Record<string,any>={};let time=0,id=0;const timers=new Map<number,Function>(),intervals:Function[]=[],beacon=vi.fn();
 for(const key of ['review-data','confirm','cancel','status','expiry','document-link','document-title','document-body'])elements[key]={disabled:true,hidden:true,textContent:'',dataset:{},addEventListener:(e:string,cb:Function)=>{elements[key][e]=cb;}};
 elements['review-data'].textContent=JSON.stringify({version:1,intent_id:'fixture',request_hash:'a'.repeat(64),csrf:'C'.repeat(43),expires_at:60000,server_now:0,input:{title:'<literal title>',markdown:'# Full body'}});
 runInNewContext(source,{document:{getElementById:(k:string)=>elements[k],body:{classList:{add:vi.fn()}}},window:{addEventListener:(k:string,v:Function)=>events[k]=v},navigator:{sendBeacon:beacon},fetch:fetcher,performance:{now:()=>time},setTimeout:(cb:Function)=>{timers.set(++id,cb);return id;},clearTimeout:(id:number)=>timers.delete(id),setInterval:(cb:Function)=>intervals.push(cb),URL,Blob});
 return{elements,events,timers,beacon,advance:(n:number)=>{time+=n;intervals.forEach(cb=>cb());},poll:async()=>{const timer=timers.entries().next().value;if(timer){timers.delete(timer[0]);timer[1]();await flush();}}};
}
describe('browser review client interrupted/repeated flows',()=>{
 it('renders content as literal text and enables confirm only after the server validates the session',async()=>{let resolve!:Function;const fetcher=vi.fn().mockReturnValue(new Promise(r=>resolve=r));const c=client(fetcher);expect(c.elements.confirm.disabled).toBe(true);resolve(response(ready));await flush();expect(c.elements.confirm.disabled).toBe(false);expect(c.elements['document-title'].textContent).toBe('<literal title>');expect(c.elements['document-body'].textContent).toBe('# Full body');});
 it('double click issues one confirm and terminal receipt remains visible after expiry',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockResolvedValueOnce(response({...ready,phase:'receipt',receipt:{status:'succeeded',url:'https://tenant.feishu.cn/docx/fixture'},can_submit:false}));const c=client(fetcher);await flush();c.elements.confirm.click();c.elements.confirm.click();await flush();expect(fetcher.mock.calls.filter(x=>x[0].endsWith('confirm'))).toHaveLength(1);expect(c.elements['document-link'].hidden).toBe(false);const text=c.elements.status.textContent;c.advance(60001);expect(c.elements.status.textContent).toBe(text);expect(c.elements.confirm.disabled).toBe(true);});
 it('lost confirm response polls local executing receipt without repeating create',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce(response({...ready,phase:'submitting',receipt:{status:'executing'},can_submit:false})).mockResolvedValueOnce(response({...ready,phase:'receipt',receipt:{status:'succeeded'},can_submit:false}));const c=client(fetcher);await flush();await c.elements.confirm.click();await flush();expect(c.timers.size).toBe(1);await c.poll();expect(c.elements.status.textContent).toContain('成功回执');expect(fetcher.mock.calls.filter(x=>x[0].endsWith('confirm'))).toHaveLength(1);expect(JSON.parse(fetcher.mock.calls.at(-1)![1].body).refresh).toBe(false);});
 it('a lost request followed by preview stays uncertain and only polls until expiry',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockRejectedValueOnce(new Error('lost')).mockResolvedValue(response(ready));const c=client(fetcher);await flush();await c.elements.confirm.click();await flush();expect(c.elements.status.textContent).toContain('提交结果尚未确认');expect(c.elements.confirm.disabled).toBe(true);expect(c.timers.size).toBe(1);c.advance(60001);expect(c.timers.size).toBe(0);expect(c.elements.status.textContent).toContain('不会重复创建');});
 it('pending provider refresh uses only status and refresh=true, never confirm',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockResolvedValueOnce(response({...ready,phase:'receipt',receipt:{status:'pending'},can_submit:false,can_refresh:true})).mockResolvedValue(response({...ready,phase:'receipt',receipt:{status:'succeeded'},can_submit:false}));const c=client(fetcher);await flush();await c.elements.confirm.click();await c.poll();expect(JSON.parse(fetcher.mock.calls.at(-1)![1].body).refresh).toBe(true);expect(fetcher.mock.calls.filter(x=>x[0].endsWith('confirm'))).toHaveLength(1);});
 it('pagehide invalidates pending confirm response; BFCache restore reads fresh status only',async()=>{let release!:Function;const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockReturnValueOnce(new Promise(r=>release=r)).mockResolvedValue(response({...ready,phase:'receipt',receipt:{status:'succeeded'},can_submit:false}));const c=client(fetcher);await flush();c.elements.confirm.click();c.events.pagehide!();const prior=c.elements.status.textContent;release(response({...ready,phase:'receipt',receipt:{status:'pending'},can_refresh:true}));await flush();expect(c.elements.status.textContent).toBe(prior);expect(c.timers.size).toBe(0);expect(c.beacon).not.toHaveBeenCalled();c.events.pageshow!({persisted:true});await flush();expect(c.elements.status.textContent).toContain('成功回执');expect(fetcher.mock.calls.filter(x=>x[0].endsWith('confirm'))).toHaveLength(1);});
 it('leaving an unsubmitted preview sends best-effort cancellation and stays inert on stale restore',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockResolvedValue(response({ok:false},false));const c=client(fetcher);await flush();c.events.pagehide!();expect(c.beacon).toHaveBeenCalledTimes(1);expect(c.elements.confirm.disabled).toBe(true);c.events.pageshow!({persisted:true});await flush();expect(c.elements.confirm.disabled).toBe(true);expect(c.elements.status.textContent).toContain('已失效');});
 it('cancel only claims success after server acknowledgement and never confirms',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockResolvedValueOnce(response({ok:true,cancelled:true}));const c=client(fetcher);await flush();await c.elements.cancel.click();expect(c.elements.status.textContent).toContain('已取消');expect(c.elements.confirm.disabled).toBe(true);expect(fetcher.mock.calls.some(x=>x[0].endsWith('confirm'))).toBe(false);});
 it('failed cancel does not claim the operation was cancelled',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(ready)).mockResolvedValueOnce(response({cancelled:false},false));const c=client(fetcher);await flush();await c.elements.cancel.click();expect(c.elements.status.textContent).toContain('可能已经提交');expect(c.elements.status.textContent).not.toContain('已取消');});
 it('read-only mode and expired sessions never enable confirm',async()=>{const c=client(vi.fn().mockResolvedValue(response({...ready,can_submit:false})));await flush();expect(c.elements.confirm.disabled).toBe(true);expect(c.elements.cancel.disabled).toBe(false);c.advance(60001);expect(c.elements.cancel.disabled).toBe(true);expect(c.elements.status.textContent).toContain('预览已到期');});
 it('does not use storage, unsafe markup rendering, or a client approval boolean',()=>{expect(source).not.toMatch(/localStorage|sessionStorage|innerHTML|eval\(|confirmed\s*:\s*true|approved\s*:\s*true/);});
});
describe('host public-key-only configuration',()=>{
 it('accepts only Ed25519 public SPKI, rejecting a private PEM before Node derives a public key',()=>{const host=generateKeyPairSync('ed25519');expect(parseDocumentReviewHostPublicKey(host.publicKey.export({format:'pem',type:'spki'}).toString()).type).toBe('public');expect(()=>parseDocumentReviewHostPublicKey(host.privateKey.export({format:'pem',type:'pkcs8'}).toString())).toThrow('Only a public');expect(()=>new DocumentReviewHandoffVerifier(host.privateKey,'https://review.example.test')).toThrow();});
 it('rejects a different key algorithm and noncanonical sites',()=>{const other=generateKeyPairSync('ec',{namedCurve:'P-256'});expect(()=>parseDocumentReviewHostPublicKey(other.publicKey.export({format:'pem',type:'spki'}).toString())).toThrow('Ed25519');const host=generateKeyPairSync('ed25519');for(const site of ['http://review.example.test','https://review.example.test/','https://review.example.test/path','https://user@review.example.test'])expect(()=>new DocumentReviewHandoffVerifier(host.publicKey,site)).toThrow();});
});
