import { beforeAll,beforeEach,afterEach,afterAll,describe,it,expect,vi } from 'vitest';
import { readFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { request as httpRequest,type Server } from 'node:http';
import { PGlite } from '@electric-sql/pglite';
import { createAgendaIssuerServer } from '../apps/mcp-server/src/issuer-server.js';
import { createAgendaServer } from '../apps/mcp-server/src/agenda-server.js';
import { PostgresAgendaIssuer } from '../packages/auth/src/durable-issuer.js';
import { FeishuBrowserLogin,FEISHU_LOGIN_SCOPES } from '../packages/auth/src/feishu-browser-login.js';
import { AuthorizationStateCipher,PostgresAuthorizationStateStore,FeishuOAuthExchange,bindFeishuTokenSdk } from '../packages/auth/src/feishu-exchange.js';
import { PostgresConnectionRepository } from '../packages/auth/src/connection-repository.js';
import { PostgresResourceAccess } from '../packages/auth/src/resource-access.js';
import { PostgresTokenStore,TokenCipher } from '../packages/auth/src/vault.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { Handles } from '../packages/policy/src/core.js';
import { pkceChallenge } from '../packages/auth/src/mock-broker.js';

async function send(url:string,options:{method?:string;headers?:Record<string,string>;body?:string}={}){return new Promise<{status:number;headers:Headers;text:string;json:()=>any}>((resolve,reject)=>{const req=httpRequest(url,{method:options.method??'GET',headers:options.headers},res=>{const chunks:Buffer[]=[];res.on('data',(chunk:Buffer)=>chunks.push(chunk));res.on('end',()=>{const headers=new Headers();for(const [key,value]of Object.entries(res.headers))if(value!==undefined)headers.set(key,Array.isArray(value)?value.join(','):value);const text=Buffer.concat(chunks).toString();resolve({status:res.statusCode!,headers,text,json:()=>JSON.parse(text)});});});req.on('error',reject);req.end(options.body);});}
const config={issuer:'https://identity.example.test/',resource:'https://mcp.example.test/mcp',clients:[{clientId:'fixture-client',name:'Synthetic <host>',redirects:['https://host.example.test/callback']},{clientId:'second-client',name:'Second host',redirects:['https://other.example.test/second-callback']}]};
const verifier='V'.repeat(43);const request={client_id:'fixture-client',redirect_uri:'https://host.example.test/callback',resource:config.resource,response_type:'code',code_challenge_method:'S256',code_challenge:pkceChallenge(verifier),scope:'calendar.read',state:'host-state'};
const tokenResponse={access_token:'synthetic-feishu-access',refresh_token:'synthetic-feishu-refresh',expires_in:3600,refresh_token_expires_in:86400,scope:FEISHU_LOGIN_SCOPES.join(' '),token_type:'Bearer'};
let db:PGlite,issuerServer:Server,resourceServer:Server,base:string,resourceBase:string;const transport=vi.fn();
const query=async(sql:string,values?:unknown[])=>{const result=await db.query(sql,values);return{...result,rowCount:result.affectedRows??result.rows.length};};
const pool={connect:async()=>({query,release(){}})};const cipher=new TokenCipher(new Map([['fixture',randomBytes(32)]]),'fixture');
const connect=new PostgresConnectionRepository(pool as never,cipher);const access=new PostgresResourceAccess({query} as never);const tokens=new PostgresTokenStore({query} as never,cipher);
const sdk=()=>createSafeSdkClient({appId:'synthetic-app',appSecret:'synthetic-secret',domain:'feishu',httpInstance:{request:transport} as never});
const port=(server:Server)=>(server.address() as {port:number}).port;
const get=(path:string,headers:Record<string,string>={})=>send(base+path,{headers:{Host:'identity.example.test',...headers}});
const post=(path:string,data:Record<string,string>,headers:Record<string,string>={})=>send(base+path,{method:'POST',headers:{Host:'identity.example.test','Content-Type':'application/x-www-form-urlencoded',...headers},body:new URLSearchParams(data).toString()});
async function start(overrides={}){const response=await get('/authorize?'+new URLSearchParams({...request,...overrides}));return{response,cookie:response.headers.get('set-cookie')?.split(';')[0]??'',target:response.headers.get('location')?new URL(response.headers.get('location')!):undefined};}
async function callback(flow:Awaited<ReturnType<typeof start>>,headers={}){return get('/oauth/feishu/callback?'+new URLSearchParams({state:flow.target!.searchParams.get('state')!,code:'synthetic-code'}),{Cookie:flow.cookie,...headers});}
async function ready(overrides={}){const flow=await start(overrides);const page=await callback(flow);expect(page.status).toBe(200);const csrf=/name="csrf" value="([^"]+)"/.exec(page.text)![1]!;return{...flow,page,csrf};}
async function consent(pending:Awaited<ReturnType<typeof ready>>,decision='allow',overrides={}){return post('/consent',{csrf:pending.csrf,decision,...overrides},{Cookie:pending.cookie,Origin:'https://identity.example.test'});}
async function exchange(code:string,overrides={}){return post('/token',{grant_type:'authorization_code',client_id:request.client_id,redirect_uri:request.redirect_uri,resource:config.resource,code,code_verifier:verifier,...overrides});}
async function issued(){const pending=await ready();const response=await consent(pending);expect(response.status).toBe(302);const code=new URL(response.headers.get('location')!).searchParams.get('code')!;const token=await exchange(code);expect(token.status).toBe(200);return{pending,code,token:token.json()};}
async function agenda(token:string){return send(resourceBase+'/mcp',{method:'POST',headers:{Host:'mcp.example.test',Accept:'application/json, text/event-stream',Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'get_agenda',arguments:{time_range:{start:'2026-10-05T00:00:00Z',end:'2026-10-06T00:00:00Z'},timezone:'UTC'}}})});}
beforeAll(async()=>{db=await PGlite.create();for(const name of ['001_connections.sql','002_oauth_link_attempts.sql','003_resource_access.sql','004_mcp_issuer.sql'])await db.exec(await readFile(new URL('../infra/migrations/'+name,import.meta.url),'utf8'));},30000);
beforeEach(async()=>{
  await db.exec('TRUNCATE feishu_connections CASCADE; TRUNCATE mcp_authorization_attempts,mcp_provider_accounts,mcp_browser_links,oauth_link_attempts');transport.mockReset();
  transport.mockImplementation(async c=>{
    if(c.url==='https://accounts.feishu.cn/oauth/v3/token')return tokenResponse;
    if(c.url==='https://open.feishu.cn/open-apis/authen/v1/user_info')return{code:0,data:{open_id:'ou_synthetic',tenant_key:'tenant_synthetic',email:'ignored-private@example.test',name:'Ignored name'}};
    if(c.url.endsWith('/calendars'))return{code:0,data:{calendar_list:[{calendar_id:'calendar1'}],has_more:false}};
    if(c.url.endsWith('/instance_view'))return{code:0,data:{items:[{event_id:'event1',summary:'Synthetic appointment',status:'confirmed',start_time:{timestamp:'1791190800'},end_time:{timestamp:'1791194400'}}]}};
    throw new Error('Unexpected network contract');
  });
  const client=sdk();const issuer=new PostgresAgendaIssuer(pool as never,config);const states=new PostgresAuthorizationStateStore({query} as never,new AuthorizationStateCipher(randomBytes(32)));
  const flow=new FeishuOAuthExchange(bindFeishuTokenSdk(client),states,{domain:'feishu',redirectUri:'https://identity.example.test/oauth/feishu/callback',allowedProviderScopes:FEISHU_LOGIN_SCOPES});
  const login=new FeishuBrowserLogin({query} as never,issuer,flow,cipher,connect,client,'synthetic-app');
  issuerServer=createAgendaIssuerServer({issuer,login,access});resourceServer=createAgendaServer({resource:config.resource,authorizationServer:config.issuer,access,tokens,handles:new Handles(randomBytes(32)),client:sdk});
  await new Promise<void>(resolve=>issuerServer.listen(0,'127.0.0.1',resolve));await new Promise<void>(resolve=>resourceServer.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+port(issuerServer);resourceBase='http://127.0.0.1:'+port(resourceServer);
});
afterEach(async()=>{for(const server of [issuerServer,resourceServer])await new Promise<void>(resolve=>{server.close(()=>resolve());server.closeAllConnections();});});
afterAll(async()=>db.close());
describe('browser OAuth -> durable token -> HTTP agenda with injected official SDK transport',()=>{
  it('allows only the current registered callback in the consent-page CSP, with its exact path',async()=>{const alpha=await ready();const expected="default-src 'none'; form-action 'self' https://host.example.test/callback; frame-ancestors 'none'; base-uri 'none'";expect(alpha.page.headers.get('content-security-policy')).toBe(expected);const beta=await ready({client_id:'second-client',redirect_uri:'https://other.example.test/second-callback'});expect(beta.page.headers.get('content-security-policy')).toBe("default-src 'none'; form-action 'self' https://other.example.test/second-callback; frame-ancestors 'none'; base-uri 'none'");expect((await get('/.well-known/oauth-authorization-server')).headers.get('content-security-policy')).toBe("default-src 'none'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'")});
  it('completes the whole flow without seeding connections, grants or MCP tokens directly',async()=>{const {token}=await issued();const result=await agenda(token.access_token);expect(result.status).toBe(200);expect(result.json().result.structuredContent.data.events[0].summary).toBe('Synthetic appointment');expect(result.json().result.structuredContent.meta).toMatchObject({source:'feishu_api',live_verified:false});const userInfo=transport.mock.calls.find(([c])=>c.url.endsWith('/user_info'))![0];expect(userInfo.headers.Authorization).toBe('Bearer '+tokenResponse.access_token);expect(transport.mock.calls.some(([c])=>JSON.stringify(c).includes(token.access_token))).toBe(false)});
  it('uses official Feishu endpoints, confidential-client secret and a separate S256 challenge',async()=>{const pending=await ready();expect(pending.target!.origin+pending.target!.pathname).toBe('https://accounts.feishu.cn/open-apis/authen/v1/authorize');expect(pending.target!.searchParams.get('scope')?.split(' ').sort()).toEqual([...FEISHU_LOGIN_SCOPES].sort());expect(pending.target!.searchParams.get('code_challenge_method')).toBe('S256');expect(pending.target!.searchParams.get('code_challenge')).not.toBe(request.code_challenge);const requestBody=transport.mock.calls[0]![0].data;expect(requestBody.client_secret==='synthetic-secret').toBe(true);expect(pkceChallenge(requestBody.code_verifier)).toBe(pending.target!.searchParams.get('code_challenge'));expect(requestBody.redirect_uri).toBe('https://identity.example.test/oauth/feishu/callback');expect(pending.page.text).not.toContain('synthetic-secret');expect(pending.page.text).not.toContain('synthetic-feishu-access')});
  it('uses HttpOnly Secure host-only cookie and an escaped explicit consent page',async()=>{const pending=await ready();expect(pending.response.headers.get('set-cookie')).toContain('__Host-feishu-link=');expect(pending.response.headers.get('set-cookie')).toContain('Secure; HttpOnly; SameSite=Lax');expect(pending.page.text).toContain('Synthetic &lt;host&gt;');expect(pending.page.headers.get('content-security-policy')).toContain("frame-ancestors 'none'");expect(pending.page.headers.get('referrer-policy')).toBe('no-referrer');expect(pending.page.text).not.toContain('ignored-private@example.test');expect((await query('SELECT * FROM oauth_grants')).rows).toHaveLength(0);expect((await query('SELECT * FROM feishu_connections')).rows).toHaveLength(0)});
  it('stores pending provider tokens encrypted and removes them when consent is denied',async()=>{const pending=await ready();const serialized=JSON.stringify((await query('SELECT * FROM mcp_browser_links')).rows);expect(serialized).not.toContain(tokenResponse.access_token);const result=await consent(pending,'deny');const location=new URL(result.headers.get('location')!);expect(location.searchParams.get('error')).toBe('access_denied');expect(location.searchParams.get('iss')).toBe(config.issuer);expect((await query('SELECT * FROM mcp_browser_links')).rows).toHaveLength(0);expect((await query('SELECT * FROM feishu_connections')).rows).toHaveLength(0)});
  it('rejects missing, wrong and duplicate browser cookies before exchanging a code',async()=>{const flow=await start();for(const Cookie of ['', '__Host-feishu-link='+'X'.repeat(43),flow.cookie+'; '+flow.cookie])expect((await callback(flow,{Cookie})).status).toBe(400);expect(transport).not.toHaveBeenCalled();expect((await callback(flow)).status).toBe(200)});
  it('rejects callback state substitution across two browser flows',async()=>{const alpha=await start();const beta=await start();expect((await callback(alpha,{Cookie:beta.cookie})).status).toBe(400);expect(transport).not.toHaveBeenCalled();expect((await callback(alpha)).status).toBe(200);expect((await callback(beta)).status).toBe(200)});
  it('never retries exchanged provider authorization codes after callback replay',async()=>{const pending=await ready();expect((await callback(pending)).status).toBe(400);expect(transport.mock.calls.filter(([c])=>c.url.includes('/oauth/v3/token'))).toHaveLength(1)});
  it.each([{open_id:'ou_synthetic'},{tenant_key:'tenant_synthetic'},{}])('rejects missing stable tenant/user identity without saving a connection',async data=>{const flow=await start();transport.mockImplementationOnce(async()=>tokenResponse).mockImplementationOnce(async()=>({code:0,data}));expect((await callback(flow)).status).toBe(400);expect((await query('SELECT * FROM feishu_connections')).rows).toHaveLength(0)});
  it('does not accept added provider permissions or missing offline/calendar consent',async()=>{for(const scope of ['calendar:calendar:read offline_access',FEISHU_LOGIN_SCOPES.join(' ')+' im:message:send']){const flow=await start();transport.mockImplementationOnce(async()=>({...tokenResponse,scope}));expect((await callback(flow)).status).toBe(400);}expect((await query('SELECT * FROM mcp_provider_accounts')).rows).toHaveLength(0)});
  it('rejects a provider token failure without reflecting its contents or attempting user_info',async()=>{const flow=await start();transport.mockRejectedValueOnce(new Error('synthetic-sensitive-provider-response'));const result=await callback(flow);expect(result.status).toBe(400);expect(result.text).not.toContain('synthetic-sensitive');expect(transport).toHaveBeenCalledTimes(1)});
  it('requires same-origin consent, the bound browser and exact CSRF value',async()=>{const pending=await ready();for(const headers of [{Cookie:pending.cookie},{Cookie:pending.cookie,Origin:'https://evil.example.test'},{Cookie:'__Host-feishu-link='+'X'.repeat(43),Origin:'https://identity.example.test'}]){expect((await post('/consent',{csrf:pending.csrf,decision:'allow'},headers)).status).toBeGreaterThanOrEqual(400);}expect((await consent(pending,'allow',{csrf:'X'.repeat(43)})).status).toBe(400);expect((await consent(pending)).status).toBe(302)});
  it('consumes consent once and preserves account mapping on explicit reauthorization',async()=>{const first=await issued();const old=(await query('SELECT subject,connection_id FROM mcp_provider_accounts')).rows[0];expect((await consent(first.pending)).status).toBe(400);const second=await issued();expect((await query('SELECT subject,connection_id FROM mcp_provider_accounts')).rows).toEqual([old]);expect((await agenda(first.token.access_token)).status).toBe(401);expect((await agenda(second.token.access_token)).status).toBe(200)});
  it('keeps different verified tenant/user pairs in different persisted accounts',async()=>{await issued();const flow=await start();transport.mockImplementationOnce(async()=>tokenResponse).mockImplementationOnce(async()=>({code:0,data:{open_id:'ou_synthetic',tenant_key:'another-tenant'}}));const page=await callback(flow);const csrf=/name="csrf" value="([^"]+)"/.exec(page.text)![1]!;expect((await consent({...flow,page,csrf})).status).toBe(302);const rows=(await query('SELECT subject,connection_id FROM mcp_provider_accounts')).rows;expect(new Set(rows.map((row:any)=>row.subject)).size).toBe(2);expect(new Set(rows.map((row:any)=>row.connection_id)).size).toBe(2)});
  it('uses SDK token validation while keeping PKCE verification atomic in the durable issuer',async()=>{const pending=await ready();const result=await consent(pending);const code=new URL(result.headers.get('location')!).searchParams.get('code')!;expect((await exchange(code,{code_verifier:'wrong'})).status).toBe(400);const valid=await exchange(code);expect(valid.status).toBe(200);expect((await exchange(code)).status).toBe(400);expect((await agenda(valid.json().access_token)).status).toBe(401)});
  it('supports refresh and revoke over SDK HTTP handlers without refreshing a Feishu token implicitly',async()=>{const {token}=await issued();const calls=transport.mock.calls.length;const result=await post('/token',{grant_type:'refresh_token',client_id:request.client_id,resource:config.resource,refresh_token:token.refresh_token});expect(result.status).toBe(200);expect(transport).toHaveBeenCalledTimes(calls);expect((await post('/revoke',{client_id:request.client_id,token:result.json().refresh_token})).status).toBe(200);expect((await agenda(result.json().access_token)).status).toBe(401)});
  it('discloses only configured registration capabilities and includes issuer on authorization errors',async()=>{const meta=(await get('/.well-known/oauth-authorization-server')).json();expect(meta.token_endpoint_auth_methods_supported).toEqual(['none']);expect(meta.code_challenge_methods_supported).toEqual(['S256']);expect(meta.authorization_response_iss_parameter_supported).toBe(true);expect(meta).not.toHaveProperty('registration_endpoint');expect(meta).not.toHaveProperty('client_id_metadata_document_supported');const wrong=await start({code_challenge_method:'plain'});expect(wrong.target!.searchParams.get('error')).toBe('invalid_request');expect(wrong.target!.searchParams.get('iss')).toBe(config.issuer);expect((await get('/register')).status).toBe(404)});
  it('rejects unregistered redirects, duplicate OAuth fields, hostile hosts and token query transport',async()=>{expect((await start({redirect_uri:'https://evil.example.test/callback'})).response.status).toBe(400);expect((await get('/authorize?'+new URLSearchParams(request)+'&client_id=other')).status).toBe(400);expect((await get('/.well-known/oauth-authorization-server',{Host:'evil.example.test'})).status).toBe(403);expect((await post('/token?access_token=synthetic',{})).status).toBe(400);expect(transport).not.toHaveBeenCalled()});
  it('expires browser callbacks before exchanging a code and prunes abandoned encrypted sessions on next login',async()=>{const flow=await start();await db.exec("UPDATE mcp_browser_links SET expires_at=now()-interval '1 second'");expect((await callback(flow)).status).toBe(400);expect(transport).not.toHaveBeenCalled();const pending=await ready();await db.exec("UPDATE mcp_browser_links SET expires_at=now()-interval '1 second'");expect((await consent(pending)).status).toBe(400);await start();expect((await query('SELECT * FROM mcp_browser_links WHERE sealed IS NOT NULL')).rows).toHaveLength(0)});
  it('refuses stale pending Feishu tokens even if the browser consent is current',async()=>{const flow=await start();transport.mockImplementationOnce(async()=>({...tokenResponse,expires_in:0.01}));const page=await callback(flow);expect(page.status).toBe(200);const csrf=/name="csrf" value="([^"]+)"/.exec(page.text)![1]!;await new Promise(resolve=>setTimeout(resolve,20));expect((await consent({...flow,page,csrf})).status).toBe(400);expect((await query('SELECT * FROM feishu_connections')).rows).toHaveLength(0)});
  it('does not follow or render provider callback error details',async()=>{const flow=await start();const result=await get('/oauth/feishu/callback?'+new URLSearchParams({state:flow.target!.searchParams.get('state')!,error:'access_denied',error_description:'synthetic-secret-detail'}),{Cookie:flow.cookie});expect(result.status).toBe(400);expect(result.text).not.toContain('synthetic-secret-detail');expect(transport).not.toHaveBeenCalled()});
  it('rejects oversized SDK token bodies, duplicate token fields and machine-to-machine grants',async()=>{expect((await post('/token',{grant_type:'client_credentials',client_id:request.client_id})).status).toBe(400);expect((await post('/token',{client_id:request.client_id,code:'X'.repeat(110000)})).status).toBe(400);const duplicate=await send(base+'/token',{method:'POST',headers:{Host:'identity.example.test','Content-Type':'application/x-www-form-urlencoded'},body:'client_id=fixture-client&client_id=other&grant_type=refresh_token'});expect(duplicate.status).toBe(400);expect(transport).not.toHaveBeenCalled()});
});
