import{describe,it,expect,vi}from'vitest';
import{randomBytes}from'node:crypto';
import{createSafeSdkClient}from'../packages/feishu/src/sdk-client.js';
import{bindSdkReads,FeishuSdkReadGateway}from'../packages/feishu/src/sdk-reads.js';
import{FeishuProviderReads}from'../packages/feishu/src/provider-reads.js';
import{FeishuProviderDomains}from'../packages/feishu/src/provider-domains.js';
import{demoIdentity}from'../packages/feishu/src/fixtures.js';
import{Handles}from'../packages/policy/src/core.js';
const range={start:'2026-10-05T09:00:00+08:00',end:'2026-10-05T10:00:00+08:00'};
function setup(){const request=vi.fn();const identity=demoIdentity();const get=vi.fn().mockResolvedValue({accessToken:'synthetic',refreshToken:'synthetic',expiresAt:Date.now()+1e6,refreshExpiresAt:Date.now()+2e6});const client=createSafeSdkClient({appId:'fixture',appSecret:'fixture',domain:'feishu',httpInstance:{request}as never});const gateway=new FeishuSdkReadGateway({identity,reads:bindSdkReads(client)},{get});const handles=new Handles(randomBytes(32));return{identity,request,get,reads:new FeishuProviderReads(gateway,handles),domains:new FeishuProviderDomains(gateway,handles)}}
describe('people and room review regressions',()=>{
 it.each([NaN, Infinity, -1, 0, 2.5, Number.MAX_SAFE_INTEGER + 1])('treats invalid room capacity %s as unknown', async capacity => { const s=setup(); s.request.mockResolvedValue({code:0,data:{rooms:[{room_id:'room1',capacity}],has_more:false}}); const result=await s.domains.roomsWithAvailability(s.identity,{time_range:range,min_capacity:1}); expect(result.rooms).toEqual([]); expect(result.partial).toBe(true); expect(result.capacity_unknown_excluded).toBe(1); expect(s.request).toHaveBeenCalledTimes(1); });
 it('rejects missing room lists rather than claiming no rooms match', async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{has_more:false}});await expect(s.domains.roomsWithAvailability(s.identity,{time_range:range})).rejects.toThrow('room page');expect(s.request).toHaveBeenCalledTimes(1)});
 it('rejects oversized room pages before any busy lookup', async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{rooms:Array.from({length:11},(_,i)=>({room_id:'room'+i,capacity:8})),has_more:true,page_token:'next'}});await expect(s.domains.roomsWithAvailability(s.identity,{time_range:range,page_size:10})).rejects.toThrow('limit');expect(s.request).toHaveBeenCalledTimes(1)});
 it.each([{start_time:'2026-10-05T09:00:00',end_time:'2026-10-05T10:00:00'},{start_time:'2026-02-30T09:00:00Z',end_time:'2026-02-30T10:00:00Z'},null])('keeps malformed multi-user busy intervals unknown: %s', async interval=>{const s=setup();s.request.mockResolvedValue({code:0,data:{freebusy_lists:[{user_id:'ou_1',freebusy_items:[interval]}]}});const result=await s.domains.freeBusy(s.identity,{people:['ou_1'],time_range:range,timezone:'Asia/Shanghai'});expect(result.complete).toBe(false);expect(result.people[0]!.known).toBe(false);expect(result.people[0]!.busy).toEqual([])});
 it('requires people.read before token acquisition and never substitutes a profile scope',async()=>{const s=setup();await expect(s.reads.people({...s.identity,scopes:['profile.read']},{query:'Alex'})).rejects.toThrow('permission');expect(s.get).not.toHaveBeenCalled();expect(s.request).not.toHaveBeenCalled()});
 it('rejects a same-tenant other-subject people session',async()=>{const s=setup();await expect(s.reads.people({...s.identity,subject:'other'},{query:'Alex'})).rejects.toThrow('different');expect(s.request).not.toHaveBeenCalled()});
 it('accepts an exact email query without choosing or contacting the single candidate',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[{id:'ou_1',meta_data:{i18n_names:{en_us:'Alex'}}}],has_more:false}});const result=await s.reads.people(s.identity,{query:'alex@example.test',locale:'en_us'});expect(result.people).toHaveLength(1);expect(s.request.mock.calls[0]![0].data).toEqual({query:'alex@example.test'});expect(result).not.toHaveProperty('selected');expect(s.request).toHaveBeenCalledTimes(1)});
 it('keeps even an empty truncated people response ambiguous',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[],has_more:true}});const result=await s.reads.people(s.identity,{query:'Alex'});expect(result.ambiguous).toBe(true);expect(result.refinement_required).toBe(true)});
 it('validates the 50-Unicode-character boundary rather than counting UTF16 code units',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[],has_more:false}});await s.reads.people(s.identity,{query:'😀'.repeat(50)});await expect(s.reads.people(s.identity,{query:'😀'.repeat(51)})).rejects.toThrow();expect(s.request).toHaveBeenCalledTimes(1)});
 it('requires calendar permission before room listing and never resolves room busy with a user_id',async()=>{const s=setup();await expect(s.domains.roomsWithAvailability({...s.identity,scopes:['people.read']},{time_range:range})).rejects.toThrow('permission');expect(s.request).not.toHaveBeenCalled()});
 it('handles offset-aware overlap and exclusive end boundaries correctly',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{freebusy_list:[{start_time:'2026-10-05T00:00:00Z',end_time:'2026-10-05T01:00:00Z'}]}}).mockResolvedValueOnce({code:0,data:{freebusy_list:[{start_time:'2026-10-05T01:30:00Z',end_time:'2026-10-05T02:30:00Z'}]}});expect((await s.domains.roomAvailability(s.identity,'room1',range)).available).toBe(true);expect((await s.domains.roomAvailability(s.identity,'room1',range)).available).toBe(false)});
 it('does not use a string-valued capacity to claim a room meets a numeric capacity requirement',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{rooms:[{room_id:'room1',capacity:'8'}],has_more:false}}).mockResolvedValue({code:0,data:{freebusy_list:[]}});const result=await s.domains.roomsWithAvailability(s.identity,{time_range:range,min_capacity:6});expect(result.rooms).toHaveLength(0);expect(result.partial).toBe(true);expect(result.capacity_unknown_excluded).toBe(1)});
 it('does not label timezone-less busy timestamps as known room availability',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{freebusy_list:[{start_time:'2026-10-05T09:00:00',end_time:'2026-10-05T10:00:00'}]}});expect((await s.domains.roomAvailability(s.identity,'room1',range)).known).toBe(false)});
 it('enforces the ten-room availability-check budget even when the provider returns too many rooms',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{rooms:Array.from({length:11},(_,i)=>({room_id:'room'+i,capacity:8})),has_more:false}}).mockResolvedValue({code:0,data:{freebusy_list:[]}});try{await s.domains.roomsWithAvailability(s.identity,{time_range:range,page_size:10})}catch{}expect(s.request.mock.calls.filter(call=>call[0].url.endsWith('/freebusy/list')).length).toBeLessThanOrEqual(10)});
 it('refuses cross-connection and changed-window room cursor before transport',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{rooms:[],has_more:true,page_token:'second'}});const first=await s.domains.roomsWithAvailability(s.identity,{time_range:range});await expect(s.domains.roomsWithAvailability(demoIdentity('beta'),{time_range:range,cursor:first.next_cursor!})).rejects.toThrow('different');await expect(s.domains.roomsWithAvailability(s.identity,{time_range:{...range,end:'2026-10-05T11:00:00+08:00'},cursor:first.next_cursor!})).rejects.toThrow('window');expect(s.request).toHaveBeenCalledTimes(1)});
 it('preserves an excluded small-room page continuation so later rooms remain reachable',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{rooms:[{room_id:'small',capacity:2}],has_more:true,page_token:'second'}}).mockResolvedValueOnce({code:0,data:{rooms:[{room_id:'large',capacity:8}],has_more:false}}).mockResolvedValueOnce({code:0,data:{freebusy_list:[]}});const first=await s.domains.roomsWithAvailability(s.identity,{time_range:range,min_capacity:6});expect(first.rooms).toHaveLength(0);expect(first.next_cursor).not.toBeNull();const second=await s.domains.roomsWithAvailability(s.identity,{time_range:range,min_capacity:6,cursor:first.next_cursor!});expect(second.rooms[0]!.room_id).toBe('large');expect(second.rooms[0]!.available).toBe(true)});
});
