import { describe, expect, it, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { ProviderReadRouter, providerReadNames, type ProviderReadServices } from '../packages/tools/src/provider-router.js';
import { ToolEngine } from '../packages/tools/src/engine.js';
import { inputSchemas, outputSchema, providerOutputSchema, readToolNames, writeToolNames } from '../packages/schemas/src/catalog.js';
import { Handles, RateLimiter } from '../packages/policy/src/core.js';
import { MockFeishuAdapter } from '../packages/feishu/src/adapter.js';
import { demoIdentity, demoWorkspaces } from '../packages/feishu/src/fixtures.js';
import { FeishuProviderReads } from '../packages/feishu/src/provider-reads.js';
import { FeishuProviderDomains } from '../packages/feishu/src/provider-domains.js';
import { FeishuProviderWorkflows } from '../packages/feishu/src/provider-workflows.js';
import { FeishuProviderBases } from '../packages/feishu/src/provider-bases.js';
import { FeishuProviderTasks } from '../packages/feishu/src/provider-tasks.js';
import { FeishuSdkReadGateway, bindSdkReads } from '../packages/feishu/src/sdk-reads.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import type { AuditEvent } from '../packages/observability/src/audit.js';

const resource='https://mcp.example.test/mcp';
const range={start:'2026-10-05T00:00:00Z',end:'2026-10-06T00:00:00Z'};
const inputs:Record<string,unknown>={get_profile:{},search:{query:'Demo',types:['doc']},fetch:{result_id:'fixture_ref'},search_people:{query:'Demo'},list_chats:{},search_messages:{query:'Demo'},get_message_thread:{message_id:'m1'},list_doc_comments:{doc_id:'doc1'},list_bases:{query:'Demo'},get_base_schema:{base_id:'base1'},query_base_records:{base_id:'base1',table_id:'table1'},get_agenda:{time_range:range,timezone:'UTC'},get_free_busy:{people:['ou1'],time_range:range,timezone:'UTC'},suggest_meeting_times:{people:['ou1'],time_range:range,timezone:'UTC',duration_minutes:30},list_meeting_rooms:{min_capacity:6},list_tasks:{},get_task:{task_id:'task1'}};
function stubSetup(limiter=new RateLimiter()){
  const identity=demoIdentity();const audit:AuditEvent[]=[];
  const names={reads:['profile','people','chats','searchMessages'],domains:['queryBase','freeBusy','roomMetadata','roomsWithAvailability'],workflows:['search','fetch','messageThread','comments','agenda','suggestMeetingTimes'],bases:['search','inspect'],tasks:['list','detail']} as const;
  const services=Object.fromEntries(Object.entries(names).map(([group,methods])=>[group,Object.fromEntries(methods.map(name=>[name,vi.fn().mockResolvedValue({source:'feishu_api',method:`${group}.${name}`,next_cursor:null})]))])) as unknown as ProviderReadServices;
  const calls=Object.values(services).flatMap(group=>Object.values(group));
  return{identity,audit,services,calls,router:new ProviderReadRouter(resource,identity,services,event=>audit.push(event),limiter),context:{identity,audience:resource,expiresAt:Date.now()+60000}};
}
function realSetup(){
  const identity=demoIdentity();const handles=new Handles(randomBytes(32));const message={message_id:'m1',chat_id:'c1',thread_id:'thread1',msg_type:'text',body:{content:'{"text":"Fixture message"}'}};
  const request=vi.fn().mockImplementation(async config=>{
    const url=config.url as string;
    if(url.endsWith('/authen/v1/user_info'))return{code:0,data:{name:'Fixture User',open_id:'ou1',tenant_key:identity.tenantId}};
    if(url.endsWith('/doc_wiki/search'))return{code:0,data:{res_units:[{entity_type:'DOC',title_highlighted:'Demo',result_meta:{token:config.data.doc_filter.doc_types.includes('BITABLE')?'base1':'doc1',doc_types:config.data.doc_filter.doc_types.includes('BITABLE')?'BITABLE':'DOCX'}}],has_more:false}};
    if(url.endsWith('/users/search'))return{code:0,data:{items:[{id:'ou1',meta_data:{i18n_names:{zh_cn:'Demo'}}}],has_more:false}};
    if(url.endsWith('/im/v1/chats'))return{code:0,data:{items:[{chat_id:'c1',name:'Chat'}],has_more:false}};
    if(url.endsWith('/messages/search'))return{code:0,data:{items:[{id:'hit1',meta_data:{message_id:'m1',chat_id:'c1'}}],has_more:false}};
    if(url.endsWith('/messages/m1'))return{code:0,data:{items:[message]}};
    if(url.endsWith('/im/v1/messages'))return{code:0,data:{items:[message],has_more:false}};
    if(url.endsWith('/documents/doc1/raw_content'))return{code:0,data:{content:'Fixture document'}};
    if(url.endsWith('/documents/doc1'))return{code:0,data:{document:{document_id:'doc1',title:'Demo'}}};
    if(url.endsWith('/files/doc1/comments'))return{code:0,data:{items:[{comment_id:'comment1',has_more:false,reply_list:{replies:[{reply_id:'reply1',content:{elements:[]}}]}}],has_more:false}};
    if(url.endsWith('/apps/base1/tables'))return{code:0,data:{items:[{table_id:'table1',name:'Table'}],has_more:false}};
    if(url.endsWith('/tables/table1/fields'))return{code:0,data:{items:[{field_id:'field1',field_name:'Text',type:1}],has_more:false}};
    if(url.endsWith('/tables/table1/records/search'))return{code:0,data:{items:[{record_id:'record1',fields:{Text:'Fixture cell'}}],has_more:false}};
    if(url.endsWith('/calendar/v4/calendars'))return{code:0,data:{calendar_list:[{calendar_id:'calendar1'}],has_more:false}};
    if(url.endsWith('/calendars/calendar1/events'))return{code:0,data:{items:[{event_id:'event1',summary:'Event',start_time:{date:'2026-10-05'},end_time:{date:'2026-10-06'}}],has_more:false}};
    if(url.endsWith('/freebusy/batch'))return{code:0,data:{freebusy_lists:[{user_id:'ou1',freebusy_items:[]}]}};
    if(url.endsWith('/freebusy/list'))return{code:0,data:{freebusy_list:[]}};
    if(url.endsWith('/vc/v1/rooms/search'))return{code:0,data:{rooms:[{room_id:'room1',name:'Room',capacity:8}],has_more:false}};
    if(url.endsWith('/task/v2/tasks'))return{code:0,data:{items:[{guid:'task1',summary:'Task',completed_at:'0'}],has_more:false}};
    if(url.endsWith('/task/v2/tasks/task1'))return{code:0,data:{task:{guid:'task1',summary:'Task',completed_at:'0'}}};
    throw new Error('Unexpected fixture endpoint');
  });
  const client=createSafeSdkClient({appId:'fixture',appSecret:'fixture',domain:'feishu',httpInstance:{request} as never});
  const gateway=new FeishuSdkReadGateway({identity,reads:bindSdkReads(client)},{get:async()=>({accessToken:'synthetic',refreshToken:'synthetic',expiresAt:Date.now()+1e6,refreshExpiresAt:Date.now()+2e6})});
  const reads=new FeishuProviderReads(gateway,handles);const domains=new FeishuProviderDomains(gateway,handles);const workflows=new FeishuProviderWorkflows(reads,domains,gateway,handles);const bases=new FeishuProviderBases(gateway,domains,handles);const tasks=new FeishuProviderTasks(gateway,handles);
  const services={reads,domains,workflows,bases,tasks};
  return{identity,handles,request,domains,router:new ProviderReadRouter(resource,identity,services),context:{identity,audience:resource,expiresAt:Date.now()+60000},mock:new ToolEngine(new MockFeishuAdapter(demoWorkspaces()),handles)};
}
describe('inert finite provider router',()=>{
  it('routes exactly seventeen read names with unchanged public write exclusion',async()=>{const s=stubSetup();expect(providerReadNames).toEqual(readToolNames);expect(providerReadNames).toHaveLength(17);for(const name of readToolNames){const result=await s.router.call(name,inputs[name],s.context);expect(result.ok,name).toBe(true);expect(result.meta).toMatchObject({source:'feishu_api',live_verified:false});}expect(s.calls.reduce((n,call)=>n+vi.mocked(call).mock.calls.length,0)).toBe(17)});
  it.each(writeToolNames)('rejects planned write %s without a service call',async name=>{const s=stubSetup();expect((await s.router.call(name,{},s.context)).error?.type).toBe('UNSUPPORTED_CAPABILITY');expect(s.calls.every(call=>vi.mocked(call).mock.calls.length===0)).toBe(true)});
  it.each([null,{},'token',{expiresAt:NaN},{expiresAt:Infinity},{expiresAt:'tomorrow'}])('rejects malformed caller context %s',async context=>{const s=stubSetup();const actual=typeof context==='object'&&context!==null&&Object.keys(context).length>0?{...s.context,...context}:context;expect((await s.router.call('get_profile',{},actual)).error?.type).toBe('AUTH_REQUIRED');expect(s.services.reads.profile).not.toHaveBeenCalled()});
  it('rejects wrong audience, expiration and bound session fields before provider calls',async()=>{const s=stubSetup();for(const context of [{...s.context,audience:'https://other.test/mcp'},{...s.context,expiresAt:0}])expect((await s.router.call('get_profile',{},context)).error?.type).toBe('AUTH_REQUIRED');for(const key of ['subject','tenantId','connectionId','domain']as const){const identity={...s.identity,[key]:key==='domain'?'lark':'other'};expect((await s.router.call('get_profile',{}, {...s.context,identity})).error?.type).toBe('PERMISSION_DENIED');}expect(s.services.reads.profile).not.toHaveBeenCalled()});
  it('does not accept identity, credentials or scopes in model arguments',async()=>{const s=stubSetup();for(const input of [{identity:s.identity},{scopes:['profile.read']},{access_token:'synthetic'}])expect((await s.router.call('get_profile',input,s.context)).error?.type).toBe('INVALID_ARGUMENT');expect((await s.router.call('get_profile',{}, {...s.context,identity:{...s.identity,scopes:[]}})).error?.type).toBe('INSUFFICIENT_SCOPE');expect(s.services.reads.profile).not.toHaveBeenCalled()});
  it('does not expose raw SDK operation names as tools',async()=>{const s=stubSetup();for(const name of ['readDocument','resolveBaseWiki','request','__proto__'])expect((await s.router.call(name,{},s.context)).error?.type).toBe('UNSUPPORTED_CAPABILITY');expect(s.calls.every(call=>vi.mocked(call).mock.calls.length===0)).toBe(true)});
  it('rejects known unsupported aggregate filters and people cursors before execution',async()=>{const s=stubSetup();for(const filter of [{owner:'ou1'},{chat_id:'c1'},{time_range:range}])expect((await s.router.call('search',{query:'Demo',...filter},s.context)).error?.type).toBe('UNSUPPORTED_CAPABILITY');expect((await s.router.call('search_people',{query:'Demo',cursor:'fake'},s.context)).error?.type).toBe('UNSUPPORTED_CAPABILITY');expect(s.services.workflows.search).not.toHaveBeenCalled();expect(s.services.reads.people).not.toHaveBeenCalled()});
  it('enforces provider-specific budgets before dispatch',async()=>{const s=stubSetup();for(const [name,input]of[['search',{query:'x'.repeat(31)}],['list_bases',{query:'x',page_size:21}],['search_people',{query:'x',page_size:31}],['get_agenda',{...inputs.get_agenda as object,page_size:21}],['list_tasks',{assignee_id:'ou1',page_size:21}],['list_meeting_rooms',{time_range:range,page_size:11}]]as const)expect((await s.router.call(name,input,s.context)).error?.type).toBe('INVALID_ARGUMENT');expect(s.calls.every(call=>vi.mocked(call).mock.calls.length===0)).toBe(true)});
  it('defaults room availability to five checks without overriding an explicit page size',async()=>{const s=stubSetup();await s.router.call('list_meeting_rooms',{time_range:range},s.context);expect(s.services.domains.roomsWithAvailability).toHaveBeenLastCalledWith(s.identity,expect.objectContaining({page_size:5}));await s.router.call('list_meeting_rooms',{time_range:range,page_size:8},s.context);expect(s.services.domains.roomsWithAvailability).toHaveBeenLastCalledWith(s.identity,expect.objectContaining({page_size:8}))});
  it('forwards target message filters and Base selection paging exactly',async()=>{const s=stubSetup();await s.router.call('search_messages',{query:'Demo',chat_id:'c1',sender_open_id:'ou1',time_range:range,page_size:7,cursor:'cursor'},s.context);expect(s.services.reads.searchMessages).toHaveBeenCalledWith(s.identity,{query:'Demo',chat_id:'c1',sender_open_id:'ou1',start:range.start,end:range.end},{page_size:7,cursor:'cursor'});await s.router.call('get_base_schema',{base_ref:'reference',page_size:5,cursor:'page2'},s.context);expect(s.services.bases.inspect).toHaveBeenCalledWith(s.identity,{base_id:undefined,base_ref:'reference',table_id:undefined},{page_size:5,cursor:'page2'})});
  it('cannot accept synthetic provenance or malformed completion as a successful provider result',async()=>{const s=stubSetup();for(const result of [{source:'synthetic_mock'},{source:'feishu_api',partial:'false'},{source:'feishu_api',complete:'true'},{source:'feishu_api',next_cursor:42},{source:'feishu_api',next_cursor:'x'.repeat(4097)}]){vi.mocked(s.services.reads.profile).mockResolvedValueOnce(result as never);expect((await s.router.call('get_profile',{},s.context)).error?.type).toBe('UPSTREAM_ERROR')}});
  it('marks partial data and incomplete busy coverage in the shared envelope',async()=>{const s=stubSetup();vi.mocked(s.services.domains.freeBusy).mockResolvedValue({source:'feishu_api',complete:false}as never);expect((await s.router.call('get_free_busy',inputs.get_free_busy,s.context)).meta.partial).toBe(true);vi.mocked(s.services.workflows.comments).mockResolvedValue({source:'feishu_api',partial:true,next_cursor:'next'}as never);expect((await s.router.call('list_doc_comments',inputs.list_doc_comments,s.context)).meta).toMatchObject({partial:true,next_cursor:'next'})});
  it('sanitizes unknown errors and retains only allowlisted audit metadata',async()=>{const s=stubSetup();vi.mocked(s.services.reads.profile).mockRejectedValue(new Error('private provider failure data'));const result=await s.router.call('get_profile',{},s.context);expect(JSON.stringify(result)).not.toContain('private provider');expect(JSON.stringify(s.audit)).not.toContain(s.identity.subject);expect(Object.keys(s.audit[0]!).sort()).toEqual(['connectionHash','durationMs','errorType','requestId','status','tool'].sort())});
  it('bounds serialized output without silently truncating provider data',async()=>{const s=stubSetup();vi.mocked(s.services.reads.profile).mockResolvedValue({source:'feishu_api',text:'x'.repeat(270000)}as never);const result=await s.router.call('get_profile',{},s.context);expect(result.error?.type).toBe('UNSUPPORTED_CAPABILITY');expect(result.data).toBeUndefined()});
  it('reuses the rate limiter and does not execute an over-limit request',async()=>{const s=stubSetup(new RateLimiter(1));expect((await s.router.call('get_profile',{},s.context)).ok).toBe(true);expect((await s.router.call('get_profile',{},s.context)).error?.type).toBe('RATE_LIMITED');expect(s.services.reads.profile).toHaveBeenCalledTimes(1)});
  it('leaves the mock HTTP imports and live-mode refusal intact',()=>{const server=readFileSync(new URL('../apps/mcp-server/src/server.ts',import.meta.url),'utf8');const main=readFileSync(new URL('../apps/mcp-server/src/main.ts',import.meta.url),'utf8');expect(server).not.toContain('provider-router');expect(main).not.toContain('provider-router');expect(main).toContain('FEISHU_MODE')});
});
describe('seventeen complete router calls over the real SDK injected transport',()=>{
  it('runs all seventeen mapped read operations without any live network or credentials',async()=>{const s=realSetup();const successful=new Set<string>();let resultId='';for(const name of readToolNames){const args=name==='fetch'?{result_id:resultId}:inputs[name];const result=await s.router.call(name,args,s.context);expect(result.ok,name+': '+JSON.stringify(result.error)).toBe(true);successful.add(name);if(name==='search')resultId=(result.data!.results as {result_id:string}[])[0]!.result_id;expect(result.meta.source).toBe('feishu_api');expect(result.meta.live_verified).toBe(false);}expect(successful.size).toBe(17);expect(s.request.mock.calls.length).toBeGreaterThan(17);expect(s.request.mock.calls.every(call=>call[0].headers.Authorization==='Bearer synthetic')).toBe(true)});
  it('keeps synthetic and provider envelopes and signed fetch references separate even with a shared signing key',async()=>{const s=realSetup();const synthetic=await s.mock.call('search',{query:demoWorkspaces().get(s.identity.connectionId)!.data.documents[0]!.title},s.identity);const provider=await s.router.call('search',{query:'Demo',types:['doc']},s.context);expect(synthetic.ok).toBe(true);expect(outputSchema.safeParse(provider).success).toBe(false);expect(providerOutputSchema.safeParse(synthetic).success).toBe(false);const providerRef=(provider.data!.results as {result_id:string}[])[0]!.result_id;expect((await s.mock.call('fetch',{result_id:providerRef},s.identity)).ok).toBe(false);const mockRef=(synthetic.data!.results as {result_id:string}[])[0]!.result_id;expect(mockRef).toBeTruthy();expect((await s.router.call('fetch',{result_id:mockRef},s.context)).ok).toBe(false)});
  it('passes a Base candidate into the existing get_base_schema tool with explicit selection',async()=>{const s=realSetup();const found=await s.router.call('list_bases',{query:'Demo'},s.context);const ref=(found.data!.candidates as {base_ref:string}[])[0]!.base_ref;const tables=await s.router.call('get_base_schema',{base_ref:ref},s.context);expect(tables).toMatchObject({ok:true,data:{coverage:'table_candidates',base_id:'base1'}});const schema=await s.router.call('get_base_schema',{base_id:'base1',table_id:'table1'},s.context);expect(schema).toMatchObject({ok:true,data:{coverage:'selected_table_schema'}})});
  it('filters room metadata by numeric capacity without making availability requests',async()=>{const s=realSetup();s.request.mockResolvedValue({code:0,data:{rooms:[{room_id:'r1',capacity:8},{room_id:'r2',capacity:'8'},{room_id:'r3',capacity:2}],has_more:false}});const result=await s.router.call('list_meeting_rooms',{min_capacity:6},s.context);expect(result.ok).toBe(true);expect(result.meta.partial).toBe(true);expect(result.data!.rooms).toMatchObject([{room_id:'r1',available:null}]);expect(s.request).toHaveBeenCalledTimes(1)});
  it('binds capacity-only room pagination and keeps unknown exclusions visible',async()=>{const s=realSetup();s.request.mockResolvedValue({code:0,data:{rooms:[{room_id:'r1',capacity:2}],has_more:true,page_token:'next'}});const first=await s.router.call('list_meeting_rooms',{min_capacity:6},s.context);expect(first.ok).toBe(true);expect(first.meta.next_cursor).not.toBeNull();const changed=await s.router.call('list_meeting_rooms',{min_capacity:8,cursor:first.meta.next_cursor!},s.context);expect(changed.error?.type).toBe('INVALID_ARGUMENT');expect(s.request).toHaveBeenCalledTimes(1)});
  it('keeps mock Base schema signed-reference and table pagination support identity-bound',async()=>{const s=realSetup();const found=await s.mock.call('search',{query:'',types:['base']},s.identity);expect(found.ok).toBe(false);const workspace=demoWorkspaces().get(s.identity.connectionId)!.data;const base=workspace.bases[0]!;const ref=s.handles.encode('resource',s.identity,{type:'base',id:base.base_id});const result=await s.mock.call('get_base_schema',{base_ref:ref,page_size:1},s.identity);expect(result.ok).toBe(true);expect(inputSchemas.get_base_schema.safeParse({base_id:base.base_id,base_ref:ref}).success).toBe(false);expect((await s.mock.call('get_base_schema',{base_ref:ref},demoIdentity('beta'))).ok).toBe(false)});
});
