import { describe, expect, it, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { FeishuProviderWorkflows } from '../packages/feishu/src/provider-workflows.js';
import { FeishuProviderDomains } from '../packages/feishu/src/provider-domains.js';
import { FeishuProviderReads } from '../packages/feishu/src/provider-reads.js';
import { FeishuSdkReadGateway, bindSdkReads } from '../packages/feishu/src/sdk-reads.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';

const window={time_range:{start:'2026-10-05T00:00:00Z',end:'2026-10-06T00:00:00Z'},timezone:'Asia/Shanghai'};
const event=(event_id:string)=>({event_id,summary:'Fixture event',start_time:{date:'2026-10-05'},end_time:{date:'2026-10-06'}});
const root={message_id:'m1',chat_id:'c1',thread_id:'thread1',msg_type:'text',body:{content:'{"text":"root"}'}};
function setup(){const request=vi.fn();const identity=demoIdentity();const handles=new Handles(randomBytes(32));const client=createSafeSdkClient({appId:'fixture',appSecret:'fixture',domain:'feishu',httpInstance:{request} as never});const gateway=new FeishuSdkReadGateway({identity,reads:bindSdkReads(client)},{get:async()=>({accessToken:'synthetic',refreshToken:'synthetic',expiresAt:Date.now()+1e6,refreshExpiresAt:Date.now()+2e6})},async()=>{});const domains=new FeishuProviderDomains(gateway,handles);return{identity,request,handles,domains,workflows:new FeishuProviderWorkflows(new FeishuProviderReads(gateway,handles),domains,gateway,handles)}}
describe('read workflow connections',()=>{
  it('does not silently omit calendars beyond the twenty-calendar traversal budget',async()=>{const s=setup();let directory=0;let eventCalls=0;s.request.mockImplementation(async config=>{if(config.url.endsWith('/calendars')){const page=directory++;return{code:0,data:{calendar_list:Array.from({length:5},(_,i)=>({calendar_id:'c'+(page*5+i)})),has_more:true,page_token:'dir'+directory}};}eventCalls++;return{code:0,data:{items:[],has_more:false}};});let cursor:string|undefined;for(let i=0;i<4;i++)cursor=(await s.workflows.agenda(s.identity,{...window,cursor})).next_cursor!;await expect(s.workflows.agenda(s.identity,{...window,cursor})).rejects.toThrow('twenty-calendar');expect(eventCalls).toBe(20)});
  it('does not send an agenda event request when the directory is genuinely empty and complete',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{calendar_list:[],has_more:false}});const result=await s.workflows.agenda(s.identity,window);expect(result).toMatchObject({events:[],traversal_complete:true,partial:false,next_cursor:null});expect(s.request).toHaveBeenCalledTimes(1)});
  it('searches and fetches Base/table metadata with search+base scopes but no docs permission',async()=>{const s=setup();const identity={...s.identity,scopes:['search.read','base.read']};s.request.mockResolvedValueOnce({code:0,data:{res_units:[{entity_type:'DOC',title_highlighted:'Base',result_meta:{token:'base1',doc_types:'BITABLE'}}],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[{table_id:'t1',name:'Sales'}],has_more:true,page_token:'next'}}).mockResolvedValueOnce({code:0,data:{items:[{table_id:'t2',name:'Other'}],has_more:false}});const found=await s.workflows.search(identity,{query:'Demo',types:['base']});const ref=found.results[0]!.result_id;const first=await s.workflows.fetch(identity,{result_id:ref});expect(first).toMatchObject({type:'base',content:null,coverage:'base_and_table_metadata',metadata:{base_id:'base1',tables:[{table_id:'t1'}]},selection_required:true});const second=await s.workflows.fetch(identity,{result_id:ref,cursor:first.next_cursor!});expect(second).toMatchObject({metadata:{tables:[{table_id:'t2'}]},next_cursor:null});expect(s.request.mock.calls.some(call=>call[0].url.includes('/records'))).toBe(false)});
  it('continues from messages into the explicit Base search domain',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{id:'hit',meta_data:{message_id:'m1'}}],has_more:false}}).mockResolvedValueOnce({code:0,data:{res_units:[{entity_type:'DOC',result_meta:{token:'base1',doc_types:'BITABLE'}}],has_more:false}});const first=await s.workflows.search(s.identity,{query:'Demo',types:['message','base']});expect(first.results[0]!.type).toBe('message');const next=await s.workflows.search(s.identity,{query:'Demo',types:['message','base'],cursor:first.next_cursor!});expect(next.results[0]!.type).toBe('base');expect(next.next_cursor).toBeNull()});
  it('reports missing Base permission without falling back to document search',async()=>{const s=setup();const identity={...s.identity,scopes:['search.read','im.read']};s.request.mockResolvedValue({code:0,data:{items:[],has_more:false}});const result=await s.workflows.search(identity,{query:'Demo',types:['message','base']});expect(result.missing_scopes).toEqual(['base.read']);expect(result.partial).toBe(true);expect(s.request.mock.calls[0]![0].url.endsWith('/messages/search')).toBe(true)});
  it('keeps Base fetch cursors bound to the exact result and connection',async()=>{const s=setup();const makeRef=(token:string)=>s.handles.encode('resource',s.identity,{provider:'feishu',kind:'base',candidate:s.handles.encode('resource',s.identity,{kind:'base_candidate',token,container:'DOC'})});const firstRef=makeRef('base1');s.request.mockResolvedValue({code:0,data:{items:[],has_more:true,page_token:'next'}});const result=await s.workflows.fetch(s.identity,{result_id:firstRef});await expect(s.workflows.fetch(s.identity,{result_id:makeRef('base2'),cursor:result.next_cursor!})).rejects.toThrow('match');await expect(s.workflows.fetch(demoIdentity('beta'),{result_id:firstRef})).rejects.toThrow('different');await expect(s.workflows.fetch({...s.identity,scopes:['search.read']},{result_id:firstRef})).rejects.toThrow('permission');expect(s.request).toHaveBeenCalledTimes(1)});
  it('pages through each calendar without pretending global chronological sorting',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'cal1@group.calendar.feishu.cn'},{calendar_id:'cal2'}],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[event('e1')],has_more:true,page_token:'events2'}}).mockResolvedValueOnce({code:0,data:{items:[event('e2')],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[event('e3')],has_more:false}});const a=await s.workflows.agenda(s.identity,window);const b=await s.workflows.agenda(s.identity,{...window,cursor:a.next_cursor!});const c=await s.workflows.agenda(s.identity,{...window,cursor:b.next_cursor!});expect([a,b,c].map(page=>page.events[0]!.event_id)).toEqual(['e1','e2','e3']);expect(c).toMatchObject({next_cursor:null,traversal_complete:true,partial:false,ordering:'calendar_then_provider_order'});expect(a.events[0]!.start).toEqual({date:'2026-10-05'});expect(s.request.mock.calls.filter(call=>call[0].url.endsWith('/calendars'))).toHaveLength(1)});
  it('keeps empty event and empty calendar-directory pages explicitly resumable',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[],has_more:true,page_token:'dir2'}}).mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'cal1'}],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:'events2'}}).mockResolvedValueOnce({code:0,data:{items:[event('e1')],has_more:false}});const a=await s.workflows.agenda(s.identity,window);expect(a.events).toEqual([]);expect(s.request).toHaveBeenCalledTimes(1);const b=await s.workflows.agenda(s.identity,{...window,cursor:a.next_cursor!});expect(b.events).toEqual([]);const c=await s.workflows.agenda(s.identity,{...window,cursor:b.next_cursor!});expect(c.events[0]!.event_id).toBe('e1');expect(c.traversal_complete).toBe(true)});
  it('preserves unavailable calendars across continuation without substituting busy data',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'denied'},{calendar_id:'allowed'}],has_more:false}}).mockRejectedValueOnce({response:{status:403}}).mockResolvedValueOnce({code:0,data:{items:[event('e1')],has_more:true,page_token:'next'}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:false}});const first=await s.workflows.agenda(s.identity,window);const last=await s.workflows.agenda(s.identity,{...window,cursor:first.next_cursor!});expect(last.unavailable_calendar_ids).toEqual(['denied']);expect(last.partial).toBe(true);expect(last.traversal_complete).toBe(true);expect(s.request.mock.calls.every(call=>!call[0].url.includes('freebusy'))).toBe(true)});
  it('stops malformed event data rather than skipping it as an empty calendar',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'c1'},{calendar_id:'c2'}],has_more:false}}).mockResolvedValueOnce({code:0,data:{has_more:false}});await expect(s.workflows.agenda(s.identity,window)).rejects.toThrow('incomplete');expect(s.request).toHaveBeenCalledTimes(2)});
  it('stops on authentication failure instead of traversing remaining calendars',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'c1'},{calendar_id:'c2'}],has_more:false}}).mockRejectedValueOnce({response:{status:401}});await expect(s.workflows.agenda(s.identity,window)).rejects.toThrow('authorization');expect(s.request).toHaveBeenCalledTimes(2)});
  it('enforces at most one directory page and five event page checks per call',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:Array.from({length:5},(_,i)=>({calendar_id:'c'+i})),has_more:true,page_token:'next'}}).mockResolvedValue({code:0,data:{items:[],has_more:false}});const result=await s.workflows.agenda(s.identity,window);expect(s.request).toHaveBeenCalledTimes(6);expect(result.events).toEqual([]);expect(result.next_cursor).not.toBeNull()});
  it('binds agenda continuation to window, timezone, page size and identity before transport',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'c1'}],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:'next'}});const first=await s.workflows.agenda(s.identity,window);for(const [identity,input]of[[s.identity,{...window,timezone:'UTC'}],[s.identity,{...window,page_size:10}],[s.identity,{...window,time_range:{...window.time_range,end:'2026-10-07T00:00:00Z'}}],[demoIdentity('beta'),window],[{...s.identity,scopes:['calendar.read']},window]] as const)await expect(s.workflows.agenda(identity,{...input,cursor:first.next_cursor!})).rejects.toThrow();expect(s.request).toHaveBeenCalledTimes(2)});
  it('rejects recurring calendar IDs across directory pages',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'c1'}],has_more:true,page_token:'next'}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:false}}).mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'c1'}],has_more:false}});const first=await s.workflows.agenda(s.identity,window);await expect(s.workflows.agenda(s.identity,{...window,cursor:first.next_cursor!})).rejects.toThrow('repeated a calendar')});
  it('rejects event cursor cycles rather than trapping traversal in one calendar',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{calendar_list:[{calendar_id:'c1'},{calendar_id:'c2'}],has_more:false}}).mockResolvedValue({code:0,data:{items:[],has_more:true,page_token:'same'}});const first=await s.workflows.agenda(s.identity,window);await expect(s.workflows.agenda(s.identity,{...window,cursor:first.next_cursor!})).rejects.toThrow('repeated')});
  it.each([{has_more:false},{calendar_list:[]},{calendar_list:[{calendar_id:'c1'},{calendar_id:'c1'}],has_more:false},{calendar_list:Array.from({length:6},(_,i)=>({calendar_id:'c'+i})),has_more:false}])('does not trust an invalid calendar directory %s',async data=>{const s=setup();s.request.mockResolvedValue({code:0,data});await expect(s.workflows.agenda(s.identity,window)).rejects.toThrow();expect(s.request).toHaveBeenCalledTimes(1)});
  it('rejects missing scopes and invalid timezones/windows before transport',async()=>{const s=setup();await expect(s.workflows.agenda({...s.identity,scopes:[]},window)).rejects.toThrow('permission');await expect(s.workflows.agenda(s.identity,{...window,timezone:'Unknown/Zone'})).rejects.toThrow();await expect(s.workflows.agenda(s.identity,{...window,time_range:{start:'2026-10-05T00:00:00',end:'2026-10-06T00:00:00'}})).rejects.toThrow();expect(s.request).not.toHaveBeenCalled()});
  it('rejects a thread A-B-A cursor cycle and preserves empty nonterminal pages',async()=>{const s=setup();for(const token of ['A','B','A'])s.request.mockResolvedValueOnce({code:0,data:{items:[root]}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:token}});const a=await s.workflows.messageThread(s.identity,'m1');expect(a.messages).toEqual([]);const b=await s.workflows.messageThread(s.identity,'m1',{cursor:a.next_cursor!});await expect(s.workflows.messageThread(s.identity,'m1',{cursor:b.next_cursor!})).rejects.toThrow('repeated')});
  it.each([{has_more:false},{items:[]},{items:[],has_more:true},{items:Array.from({length:21},()=>root),has_more:false},{items:[root,root],has_more:false}])('rejects malformed or duplicate thread pages %s',async data=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[root]}}).mockResolvedValueOnce({code:0,data});await expect(s.workflows.messageThread(s.identity,'m1')).rejects.toThrow()});
  it('requires root chat identity before reading a thread container',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[{...root,chat_id:undefined}]}});await expect(s.workflows.messageThread(s.identity,'m1')).rejects.toThrow('identify its chat');expect(s.request).toHaveBeenCalledTimes(1)});
});
