import { describe, expect, it, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { FeishuProviderBases } from '../packages/feishu/src/provider-bases.js';
import { FeishuProviderDomains } from '../packages/feishu/src/provider-domains.js';
import { FeishuSdkReadGateway, bindSdkReads } from '../packages/feishu/src/sdk-reads.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';

const candidate = (token='base1',entity_type='DOC',doc_types='BITABLE') => ({entity_type,title_highlighted:'<h>Demo</h> Base',result_meta:{token,doc_types,url:'https://tenant.feishu.cn/base/base1'}});
function setup(){const request=vi.fn();const get=vi.fn().mockResolvedValue({accessToken:'synthetic',refreshToken:'synthetic',expiresAt:Date.now()+1e6,refreshExpiresAt:Date.now()+2e6});const identity={...demoIdentity(),scopes:['base.read']};const handles=new Handles(randomBytes(32));const client=createSafeSdkClient({appId:'fixture',appSecret:'fixture',domain:'feishu',httpInstance:{request} as never});const gateway=new FeishuSdkReadGateway({identity,reads:bindSdkReads(client)},{get});const domains=new FeishuProviderDomains(gateway,handles);return{identity,request,get,gateway,handles,domains,bases:new FeishuProviderBases(gateway,domains,handles)}}
describe('bounded Base candidate to table workflow',()=>{
  it.each([{has_more:false},{items:[]},{items:[{record_id:'r1'}],has_more:false},{items:[{record_id:'r1',fields:{}},{record_id:'r1',fields:{}}],has_more:false}])('does not claim missing or malformed record pages are complete: %s',async data=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{field_id:'f1',field_name:'Amount',type:2}],has_more:false}}).mockResolvedValueOnce({code:0,data});await expect(s.domains.queryBase(s.identity,{base_id:'base1',table_id:'t1'})).rejects.toThrow()});
  it('does not project inherited object properties as provider cell values',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{field_id:'f1',field_name:'constructor',type:1}],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[{record_id:'r1',fields:{}}],has_more:false}});expect((await s.domains.queryBase(s.identity,{base_id:'base1',table_id:'t1'})).records[0]!.fields.f1!.value).toBeNull()});
  it.each([null,{field_id:5,field_name:'Amount',type:2},{field_id:'f1',field_name:5,type:2}])('rejects malformed schema field %s',async field=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[field],has_more:false}});await expect(s.bases.inspect(s.identity,{base_id:'base1',table_id:'t1'})).rejects.toThrow('schema')});
  it('closes keyword candidate -> explicit table -> schema -> projected record read with base-only logical permission',async()=>{
    const s=setup();s.request.mockResolvedValueOnce({code:0,data:{res_units:[candidate()],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[{table_id:'table1',name:'Sales'}],has_more:false}}).mockResolvedValue({code:0,data:{items:[{field_id:'field1',field_name:'Amount',type:2}],has_more:false}});
    const found=await s.bases.search(s.identity,'Demo');expect(found.candidates[0]!.title).toBe('Demo Base');expect(found.selection_required).toBe(true);
    const selected=await s.bases.inspect(s.identity,{base_ref:found.candidates[0]!.base_ref});expect(selected).toMatchObject({base_id:'base1',coverage:'table_candidates',tables:[{table_id:'table1',name:'Sales'}],selection_required:true});
    const schema=await s.bases.inspect(s.identity,{base_id:'base1',table_id:'table1'});expect(schema).toMatchObject({coverage:'selected_table_schema',selection_required:false,fields:[{field_id:'field1'}]});
    s.request.mockResolvedValueOnce({code:0,data:{items:[{field_id:'field1',field_name:'Amount',type:2}],has_more:false}}).mockResolvedValueOnce({code:0,data:{items:[{record_id:'r1',fields:{Amount:10,Unrequested:'hidden'}}],has_more:false}});
    const records=await s.domains.queryBase(s.identity,{base_id:'base1',table_id:'table1',fields:['field1'],filter:{field_id:'field1',operator:'gt',value:5}});expect(records.records[0]!.fields.field1!.value).toBe(10);expect(JSON.stringify(records)).not.toContain('hidden');
    expect(s.request.mock.calls[0]![0]).toMatchObject({method:'POST',url:'https://open.feishu.cn/open-apis/search/v2/doc_wiki/search',data:{doc_filter:{doc_types:['BITABLE']},wiki_filter:{doc_types:['BITABLE']}}});expect(s.request.mock.calls.every(call=>call[0].headers.Authorization==='Bearer synthetic')).toBe(true);
  });
  it('resolves a Wiki node to verified bitable obj_token before table lookup',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{res_units:[candidate('wiki1','WIKI')],has_more:false}}).mockResolvedValueOnce({code:0,data:{node:{obj_type:'bitable',obj_token:'actualBase',title:'Base'}}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:false}});const found=await s.bases.search(s.identity,'Demo');expect(found.candidates[0]).toMatchObject({base_id:null,wiki_node_token:'wiki1',resolved:false});const result=await s.bases.inspect(s.identity,{base_ref:found.candidates[0]!.base_ref});expect(result.base_id).toBe('actualBase');expect(s.request.mock.calls[1]![0]).toMatchObject({method:'GET',url:'https://open.feishu.cn/open-apis/wiki/v2/spaces/node_by_token',params:{token:'wiki1'}});expect(s.request.mock.calls[2]![0].url).toBe('https://open.feishu.cn/open-apis/bitable/v1/apps/actualBase/tables')});
  it('does not infer all-Base enumeration or allow over-limit search inputs',async()=>{const s=setup();await expect(s.bases.search(s.identity,undefined)).rejects.toThrow('All-Base');await expect(s.bases.search(s.identity,'')).rejects.toThrow();await expect(s.bases.search(s.identity,'😀'.repeat(31))).rejects.toThrow();await expect(s.bases.search(s.identity,'Demo',{page_size:21})).rejects.toThrow();expect(s.request).not.toHaveBeenCalled()});
  it('accepts the exact 30-Unicode-character boundary',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{res_units:[],has_more:false}});await s.bases.search(s.identity,'😀'.repeat(30));expect(s.request).toHaveBeenCalledTimes(1)});
  it('does not automatically choose a sole candidate if later pages exist',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{res_units:[candidate()],has_more:true,page_token:'next'}});const result=await s.bases.search(s.identity,'Demo');expect(result.ambiguous).toBe(true);expect(result).not.toHaveProperty('selected');expect(result.next_cursor).not.toBeNull()});
  it('does not let a base-only caller widen fixed search filters to DOCX',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{res_units:[candidate()],has_more:false}});await s.gateway.call('searchBases',{data:{query:'Demo',page_size:5,doc_filter:{doc_types:['DOCX']},wiki_filter:{doc_types:['DOCX']}}} as never,s.identity);expect(s.request.mock.calls[0]![0].data.doc_filter.doc_types).toEqual(['BITABLE']);await expect(s.gateway.call('readDocument',{path:{document_id:'doc1'}},s.identity)).rejects.toThrow('permission')});
  it('rejects provider DOCX data inside a Base search even at the gateway',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{res_units:[candidate('privateDoc','DOC','DOCX')],has_more:false}});await expect(s.gateway.call('searchBases',{data:{query:'Demo',page_size:5}},s.identity)).rejects.toThrow('could not');expect(s.request).toHaveBeenCalledTimes(1)});
  it.each([{obj_type:'docx',obj_token:'doc1',title:'Wrong domain'},{obj_type:'bitable'},{obj_type:'bitable',obj_token:'../traversal'}])('never forwards invalid resolved Wiki objects %s to Base tables',async node=>{const s=setup();const base_ref=s.handles.encode('resource',s.identity,{kind:'base_candidate',token:'wiki1',container:'WIKI'});s.request.mockResolvedValue({code:0,data:{node}});await expect(s.bases.inspect(s.identity,{base_ref})).rejects.toThrow();expect(s.request).toHaveBeenCalledTimes(1)});
  it('keeps Base candidates connection-bound and denies missing Base permission before tokens',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{res_units:[candidate()],has_more:false}});const found=await s.bases.search(s.identity,'Demo');await expect(s.bases.inspect({...demoIdentity('beta'),scopes:['base.read']},{base_ref:found.candidates[0]!.base_ref})).rejects.toThrow('different');await expect(s.bases.search({...s.identity,scopes:['docs.read']},'Demo')).rejects.toThrow('permission');expect(s.get).toHaveBeenCalledTimes(1)});
  it('requires exactly one explicit Base selection and rejects arbitrary URL references',async()=>{const s=setup();for(const input of [{},{base_id:'base1',base_ref:'bad'},{base_ref:'https://attacker.example/base'}])await expect(s.bases.inspect(s.identity,input)).rejects.toThrow();expect(s.request).not.toHaveBeenCalled()});
  it('does not auto-select one table or hide later empty pages',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:'next'}}).mockResolvedValueOnce({code:0,data:{items:[{table_id:'t1',name:'Only table'}],has_more:false}});const first=await s.bases.inspect(s.identity,{base_id:'base1'});expect(first.selection_required).toBe(true);const second=await s.bases.inspect(s.identity,{base_id:'base1'},{cursor:'next_cursor' in first?first.next_cursor!:undefined});expect(second.selection_required).toBe(true);expect(s.request.mock.calls[1]![0].params.page_token).toBe('next')});
  it('rejects a table cursor on another Wiki before any resolution call',async()=>{const s=setup();const base_ref=s.handles.encode('resource',s.identity,{kind:'base_candidate',token:'wiki1',container:'WIKI'});s.request.mockResolvedValueOnce({code:0,data:{node:{obj_type:'bitable',obj_token:'base1'}}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:'next'}});const first=await s.bases.inspect(s.identity,{base_ref});const other=s.handles.encode('resource',s.identity,{kind:'base_candidate',token:'wiki2',container:'WIKI'});await expect(s.bases.inspect(s.identity,{base_ref:other},{cursor:'next_cursor' in first?first.next_cursor!:undefined})).rejects.toThrow('selection');expect(s.request).toHaveBeenCalledTimes(2)});
  it('rejects a Wiki retargeted between table pages before querying the new Base',async()=>{const s=setup();const base_ref=s.handles.encode('resource',s.identity,{kind:'base_candidate',token:'wiki1',container:'WIKI'});s.request.mockResolvedValueOnce({code:0,data:{node:{obj_type:'bitable',obj_token:'base1'}}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:'next'}}).mockResolvedValueOnce({code:0,data:{node:{obj_type:'bitable',obj_token:'base2'}}});const first=await s.bases.inspect(s.identity,{base_ref});await expect(s.bases.inspect(s.identity,{base_ref},{cursor:'next_cursor' in first?first.next_cursor!:undefined})).rejects.toThrow('query');expect(s.request).toHaveBeenCalledTimes(3)});
  it.each([{has_more:false},{res_units:[candidate(),candidate()],has_more:false},{res_units:[candidate('base1','UNKNOWN')],has_more:false},{res_units:Array.from({length:21},(_,i)=>candidate('b'+i)),has_more:false}])('rejects missing, duplicate or oversized Base search results %s',async data=>{const s=setup();s.request.mockResolvedValue({code:0,data});await expect(s.bases.search(s.identity,'Demo')).rejects.toThrow()});
  it('rejects repeated Base candidate pagination tokens',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{res_units:[],has_more:true,page_token:'same'}});const first=await s.bases.search(s.identity,'Demo');await expect(s.bases.search(s.identity,'Demo',{cursor:first.next_cursor!})).rejects.toThrow('repeated')});
  it.each([{has_more:false},{items:[]},{items:[{field_id:'f1',field_name:'Amount',type:2.5}],has_more:false}])('does not treat missing or malformed field schemas as complete %s',async data=>{const s=setup();s.request.mockResolvedValue({code:0,data});await expect(s.bases.inspect(s.identity,{base_id:'base1',table_id:'t1'})).rejects.toThrow('schema')});
});
