import { describe, expect, it, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { bindSdkReads, FeishuSdkReadGateway, operationScopes, ProviderError } from '../packages/feishu/src/sdk-reads.js';
import { FeishuProviderReads } from '../packages/feishu/src/provider-reads.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';

function setup(response: unknown = { code: 0, data: {} }) {
  const request = vi.fn().mockResolvedValue(response);
  // Explicit all-synthetic credentials and injected transport: no environment access or outbound request.
  const client = createSafeSdkClient({ appId: 'synthetic-app', appSecret: 'synthetic-app-secret', domain: 'feishu', httpInstance: { request } as never });
  const identity = demoIdentity();
  const get = vi.fn().mockResolvedValue({ accessToken: 'synthetic-user-token', refreshToken: 'synthetic-refresh-token', expiresAt: Date.now() + 1_000_000, refreshExpiresAt: Date.now() + 2_000_000 });
  const sleep = vi.fn().mockResolvedValue(undefined);
  const gateway = new FeishuSdkReadGateway({ identity, reads: bindSdkReads(client) }, { get }, sleep);
  const reads = new FeishuProviderReads(gateway, new Handles(randomBytes(32)));
  return { request, client, identity, get, gateway, reads, sleep };
}
describe('official SDK transport contracts, no live service', () => {
  it('binds thirty-one bounded provider read operations with no generic/write operation', () => { const s = setup(); expect(Object.keys(bindSdkReads(s.client))).toHaveLength(31); expect(Object.keys(operationScopes)).toHaveLength(31); });
  it('uses the official fixed contact search contract and does not guess a recipient', async () => { const s = setup({ code: 0, data: { items: [{ id: 'ou_1', meta_data: { i18n_names: { zh_cn: '同名测试' } } }, { id: 'ou_2', meta_data: { i18n_names: { zh_cn: '同名测试' } } }], has_more: false } }); const result = await s.reads.people(s.identity, { query: '同名测试' }); expect(result.ambiguous).toBe(true); expect(result.people.map(person => person.open_id)).toEqual(['ou_1', 'ou_2']); expect(s.request.mock.calls[0]![0]).toMatchObject({ url: 'https://open.feishu.cn/open-apis/contact/v3/users/search', method: 'POST', data: { query: '同名测试' }, params: { page_size: 20 } }); expect(s.request.mock.calls[0]![0].headers.Authorization === 'Bearer synthetic-user-token').toBe(true); });
  it('reports incomplete people search instead of inventing cursor pagination or uniqueness', async () => { const s = setup({ code: 0, data: { items: [{ id: 'ou_1' }], has_more: true } }); const result = await s.reads.people(s.identity, { query: 'demo' }); expect(result.ambiguous).toBe(true); expect(result.refinement_required).toBe(true); expect(result.next_cursor).toBeNull(); });
  it('rejects unknown people search cursor and respects the documented character/page limits', async () => { const s = setup(); await expect(s.reads.people(s.identity, { query: 'a'.repeat(51) })).rejects.toThrow(); await expect(s.reads.people(s.identity, { query: 'x', page_size: 31 })).rejects.toThrow(); await expect(s.reads.people(s.identity, { query: 'x', cursor: 'not-supported' } as never)).rejects.toThrow(); expect(s.request).not.toHaveBeenCalled(); });
  it('does not expose extra profile/contact fields in people results', async () => { const s = setup({ code: 0, data: { items: [{ id: 'ou_1', meta_data: { i18n_names: { en_us: 'Demo' }, mail_address: 'private@example.test', description: 'private signature' } }], has_more: false } }); const result = await s.reads.people(s.identity, { query: 'demo', locale: 'en_us' }); expect(result.people[0]!.display_name).toBe('Demo'); expect(JSON.stringify(result)).not.toContain('private@example.test'); expect(JSON.stringify(result)).not.toContain('private signature'); });
  it('uses the official profile endpoint and forces user authorization', async () => {
    const s = setup({ code: 0, data: { name: 'Demo', open_id: 'person-1', tenant_key: demoIdentity().tenantId, email: 'private@example.test', mobile: 'synthetic' } });
    const profile = await s.reads.profile(s.identity);
    expect(profile).toMatchObject({ display_name: 'Demo', source: 'feishu_api' }); expect(profile).not.toHaveProperty('email'); expect(profile).not.toHaveProperty('mobile');
    const config = s.request.mock.calls[0]![0]; expect(config.url).toBe('https://open.feishu.cn/open-apis/authen/v1/user_info'); expect(config.method).toBe('GET');
    // Assert presence/selection without ever emitting the header value in test output.
    expect(config.headers.Authorization === 'Bearer synthetic-user-token').toBe(true);
    expect(s.request).toHaveBeenCalledTimes(1); // A tenant-access-token request would add a call.
  });
  it('rejects provider tenant mismatch and cuts off forged domain/session before transport', async () => { const s = setup({ code: 0, data: { name: 'Demo', open_id: 'p', tenant_key: 'wrong' } }); await expect(s.reads.profile(s.identity)).rejects.toThrow('tenant'); s.request.mockClear(); await expect(s.reads.profile({ ...s.identity, domain: 'lark' })).rejects.toThrow('different'); expect(s.request).not.toHaveBeenCalled(); });
  it('requires scopes and a valid token before calling the provider', async () => { const s = setup(); await expect(s.gateway.call('listTasks', {}, { ...s.identity, scopes: [] })).rejects.toThrow('permission'); expect(s.get).not.toHaveBeenCalled(); s.get.mockResolvedValue({ accessToken: '', expiresAt: 0 }); await expect(s.gateway.call('listTasks', {}, s.identity)).rejects.toThrow('authorization'); expect(s.request).not.toHaveBeenCalled(); });
  it('sends actual chat pagination field names and rejects cross-connection cursors', async () => { const s = setup({ code: 0, data: { items: [{ chat_id: 'oc_fixture', name: 'Demo', tenant_key: 'not-returned' }], has_more: true, page_token: 'opaque-provider-page' } }); const first = await s.reads.chats(s.identity, 'Demo', { page_size: 5 }); expect(s.request.mock.calls[0]![0].params).toMatchObject({ query: 'Demo', page_size: 5, user_id_type: 'open_id' }); s.request.mockResolvedValueOnce({ code: 0, data: { items: [], has_more: false } }); await s.reads.chats(s.identity, 'Demo', { page_size: 5, cursor: first.next_cursor! }); expect(s.request.mock.calls[1]![0].params.page_token).toBe('opaque-provider-page'); await expect(s.reads.chats(demoIdentity('beta'), 'Demo', { page_size: 5, cursor: first.next_cursor! })).rejects.toThrow('different'); });
  it('does not silently terminate an inconsistent upstream page', async () => { const s = setup({ code: 0, data: { items: [], has_more: true } }); await expect(s.reads.chats(s.identity, undefined)).rejects.toThrow('pagination'); });
  it('uses search/v2/doc_wiki request and response fields, not guessed files/items', async () => { const s = setup({ code: 0, data: { has_more: false, res_units: [{ title_highlighted: '<b>Demo</b>', summary_highlighted: 'Notes', result_meta: { token: 'doc_fixture', doc_types: 'DOCX', url: 'https://tenant.feishu.cn/docx/doc_fixture' } }] } }); const result = await s.reads.searchDocuments(s.identity, 'Demo'); expect(s.request.mock.calls[0]![0]).toMatchObject({ method: 'POST', url: 'https://open.feishu.cn/open-apis/search/v2/doc_wiki/search', data: { query: 'Demo', page_size: 20 } }); expect(result.results[0]).toMatchObject({ title: 'Demo', resource_token: 'doc_fixture' }); });
  it('honors verified Drive search query/page limits before transport', async () => { const s = setup(); await expect(s.reads.searchDocuments(s.identity, 'x'.repeat(31))).rejects.toThrow(); await expect(s.reads.searchDocuments(s.identity, 'x', ['DOCX'], { page_size: 21 })).rejects.toThrow(); expect(s.request).not.toHaveBeenCalled(); });
  it('rejects untrusted returned URLs without following them', async () => { const s = setup({ code: 0, data: { has_more: false, res_units: [{ result_meta: { token: 'doc', doc_types: 'DOCX', url: 'https://attacker.example/resource' } }] } }); expect((await s.reads.searchDocuments(s.identity, 'x')).results[0]!.url).toBeNull(); expect(s.request).toHaveBeenCalledTimes(1); });
  it('uses the current IM search endpoint and explicit second-based time filter', async () => { const s = setup({ code: 0, data: { items: [{ id: 'r1', display_info: 'Synthetic match', meta_data: { message_id: 'om_fixture', chat_id: 'oc_fixture', from_id: 'ou_fixture' } }], has_more: false } }); const result = await s.reads.searchMessages(s.identity, { query: 'hello', chat_id: 'oc_fixture', start: '2026-10-05T00:00:00Z', end: '2026-10-06T00:00:00Z' }); expect(s.request.mock.calls[0]![0]).toMatchObject({ url: 'https://open.feishu.cn/open-apis/im/v1/messages/search', data: { filter: { chat_ids: ['oc_fixture'], time_range: { start_time: '1791158400', end_time: '1791244800' } } } }); expect(result.messages[0]!.message_id).toBe('om_fixture'); });
  it('fetches document metadata and raw content with concrete docx paths', async () => { const s = setup(); s.request.mockImplementation(async config => config.url.endsWith('/raw_content') ? { code: 0, data: { content: 'Provider fixture only' } } : { code: 0, data: { document: { document_id: 'doc_fixture', title: 'Demo' } } }); const doc = await s.reads.document(s.identity, 'doc_fixture'); expect(doc.content).toBe('Provider fixture only'); expect(s.request.mock.calls.map(call => call[0].url).sort()).toEqual(['https://open.feishu.cn/open-apis/docx/v1/documents/doc_fixture', 'https://open.feishu.cn/open-apis/docx/v1/documents/doc_fixture/raw_content'].sort()); });
  it('uses task v2 guid fields and discloses assigned-to-me list coverage', async () => { const s = setup({ code: 0, data: { items: [{ guid: 'task_fixture', summary: 'Fixture task', completed_at: '0' }], has_more: false } }); const result = await s.reads.tasks(s.identity, false); expect(s.request.mock.calls[0]![0].url).toBe('https://open.feishu.cn/open-apis/task/v2/tasks'); expect(result.tasks[0]!.task_id).toBe('task_fixture'); expect(result.coverage).toBe('tasks_assigned_to_current_user'); });
  it('routes a task detail to task_guid, not the obsolete task_id path', async () => { const s = setup({ code: 0, data: { task: { guid: 'task_fixture', summary: 'Task' } } }); await s.reads.task(s.identity, 'task_fixture'); expect(s.request.mock.calls[0]![0].url).toBe('https://open.feishu.cn/open-apis/task/v2/tasks/task_fixture'); });
  it('passes SDK-typed Base schema/record payloads without manufacturing field IDs', async () => { const s = setup({ code: 0, data: { items: [], has_more: false } }); await s.reads.baseFields(s.identity, { path: { app_token: 'app_fixture', table_id: 'table_fixture' }, params: { page_size: 20 } }); expect(s.request.mock.calls[0]![0].url).toBe('https://open.feishu.cn/open-apis/bitable/v1/apps/app_fixture/tables/table_fixture/fields'); });
  it('preserves the calendar-specific path and time range parameters', async () => { const s = setup({ code: 0, data: { items: [], has_more: false } }); await s.reads.calendarEvents(s.identity, { path: { calendar_id: 'calendar_fixture' }, params: { start_time: '1791158400', end_time: '1791244800', page_size: 20 } }); expect(s.request.mock.calls[0]![0]).toMatchObject({ url: 'https://open.feishu.cn/open-apis/calendar/v4/calendars/calendar_fixture/events', params: { start_time: '1791158400' } }); });
  it('retries actual Axios HTTP failures with a bounded Retry-After', async () => { const s = setup(); s.request.mockRejectedValueOnce({ response: { status: 429, headers: { 'retry-after': '999' }, data: 'private-content' }, config: { data: 'private-secret' } }).mockResolvedValue({ code: 0, data: {} }); await s.gateway.call('profile', {}, s.identity); expect(s.sleep.mock.calls[0]![0]).toBe(10_000); expect(s.request).toHaveBeenCalledTimes(2); });
  it('sanitizes HTTP and nonzero Feishu envelope failures without retrying ambiguous business errors', async () => { const s = setup({ code: 1234567, msg: 'private response', data: {} }); try { await s.gateway.call('profile', {}, s.identity); throw new Error('Expected failure'); } catch (error) { expect(error).toBeInstanceOf(ProviderError); expect(JSON.stringify(error)).not.toContain('private response'); } expect(s.request).toHaveBeenCalledTimes(1); });
  it.each([401, 403, 404])('does not retry HTTP %s', async status => { const s = setup(); s.request.mockRejectedValue({ response: { status }, config: { data: 'private' } }); await expect(s.gateway.call('profile', {}, s.identity)).rejects.toThrow(); expect(s.request).toHaveBeenCalledTimes(1); });
});
