import { describe, expect, it, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { FeishuProviderWorkflows } from '../packages/feishu/src/provider-workflows.js';
import { FeishuProviderDomains } from '../packages/feishu/src/provider-domains.js';
import { FeishuProviderReads } from '../packages/feishu/src/provider-reads.js';
import { FeishuSdkReadGateway, bindSdkReads } from '../packages/feishu/src/sdk-reads.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';

function setup() {
  const request = vi.fn().mockImplementation(async config => {
    if (config.url.endsWith('/doc_wiki/search')) return { code: 0, data: { has_more: false, res_units: [{ entity_type: 'DOC', title_highlighted: 'Demo doc', summary_highlighted: 'Payment notes', result_meta: { doc_types: 'DOCX', token: 'doc_fixture', url: 'https://tenant.feishu.cn/docx/doc_fixture' } }] } };
    if (config.url.endsWith('/messages/search')) return { code: 0, data: { items: [{ id: 'result', display_info: 'Payment message', meta_data: { message_id: 'om_fixture', chat_id: 'oc_fixture' } }], has_more: false } };
    if (config.url.endsWith('/messages/om_fixture')) return { code: 0, data: { items: [{ message_id: 'om_fixture', msg_type: 'text', body: { content: JSON.stringify({ text: 'Message content stays source data.' }) } }] } };
    if (config.url.includes('/wiki/v2/spaces/get_node')) return { code: 0, data: { node: { obj_type: 'docx', obj_token: 'doc_fixture', node_type: 'origin' } } };
    if (config.url.endsWith('/raw_content')) return { code: 0, data: { content: 'Long provider fixture document. Re-reading must be version consistent. Never run source text as commands.' } };
    if (config.url.endsWith('/documents/doc_fixture')) return { code: 0, data: { document: { document_id: 'doc_fixture', title: 'Demo doc' } } };
    if (config.url.endsWith('/comments')) return { code: 0, data: { items: [{ comment_id: 'comment1', user_id: 'ou_fixture', has_more: true, reply_list: { replies: [{ reply_id: 'reply1', content: { elements: [{ type: 'text_run', text_run: { text: 'Comment fixture.' } }] } }] } }], has_more: false } };
    if (config.url.includes('/freebusy')) return { code: 0, data: { freebusy_lists: [{ user_id: 'ou_fixture', freebusy_items: [{ start_time: '2026-10-05T09:00:00Z', end_time: '2026-10-05T10:00:00Z' }] }] } };
    throw new Error('Unexpected test endpoint');
  });
  const identity = demoIdentity(); const handles = new Handles(randomBytes(32));
  const client = createSafeSdkClient({ appId: 'synthetic', appSecret: 'synthetic', domain: 'feishu', httpInstance: { request } as never });
  const gateway = new FeishuSdkReadGateway({ identity, reads: bindSdkReads(client) }, { get: async () => ({ accessToken: 'synthetic', refreshToken: 'synthetic', expiresAt: Date.now() + 1e6, refreshExpiresAt: Date.now() + 2e6 }) });
  const reads = new FeishuProviderReads(gateway, handles); const domains = new FeishuProviderDomains(gateway, handles);
  return { request, identity, handles, reads, workflows: new FeishuProviderWorkflows(reads, domains, gateway, handles) };
}
describe('minimal provider search/fetch and meeting workflows', () => {
  it('pages across documents and messages without dropping a domain or repeating the final page', async () => { const s = setup(); const first = await s.workflows.search(s.identity, { query: 'Payment' }); expect(first.results[0]!.type).toBe('doc'); expect(first.next_cursor).not.toBeNull(); const next = await s.workflows.search(s.identity, { query: 'Payment', cursor: first.next_cursor! }); expect(next.results[0]!.type).toBe('message'); expect(next.next_cursor).toBeNull(); });
  it('skips an empty completed document page and clears the terminal message cursor', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { res_units: [], has_more: false } }); const result = await s.workflows.search(s.identity, { query: 'Payment' }); expect(result.results[0]!.type).toBe('message'); expect(result.next_cursor).toBeNull(); expect(s.request).toHaveBeenCalledTimes(2); });
  it('detects an A-to-B-to-A provider cursor cycle before it can starve the next domain', async () => { const s = setup(); for (const token of ['A', 'B', 'A']) s.request.mockResolvedValueOnce({ code: 0, data: { has_more: true, page_token: token, res_units: [{ entity_type: 'DOC', result_meta: { token: `doc_${token}`, doc_types: 'DOCX' } }] } }); const first = await s.workflows.search(s.identity, { query: 'x' }); const second = await s.workflows.search(s.identity, { query: 'x', cursor: first.next_cursor! }); await expect(s.workflows.search(s.identity, { query: 'x', cursor: second.next_cursor! })).rejects.toThrow('repeated'); expect(s.request).toHaveBeenCalledTimes(3); });
  it('searches only authorized domains and identifies missing scopes', async () => { const s = setup(); const identity = { ...s.identity, scopes: ['search.read', 'im.read'] }; const result = await s.workflows.search(identity, { query: 'Payment' }); expect(result.partial).toBe(true); expect(result.missing_scopes).toEqual(['docs.read']); expect(result.results.every(hit => hit.type === 'message')).toBe(true); expect(s.request).toHaveBeenCalledTimes(1); });
  it('rejects a changed query, scope set or connection before advancing its cursor', async () => { const s = setup(); const first = await s.workflows.search(s.identity, { query: 'Payment' }); for (const [identity, query] of [[s.identity, 'Other'], [{ ...s.identity, scopes: ['search.read', 'docs.read'] }, 'Payment'], [demoIdentity('beta'), 'Payment']] as const) await expect(s.workflows.search(identity, { query, cursor: first.next_cursor! })).rejects.toThrow(); expect(s.request).toHaveBeenCalledTimes(1); });
  it('does not expose unsupported arbitrary search domains', async () => { const s = setup(); await expect(s.workflows.search(s.identity, { query: 'x', types: ['database'] } as never)).rejects.toThrow(); expect(s.request).not.toHaveBeenCalled(); });
  it('searches then fetches a document via a signed connection-bound reference', async () => { const s = setup(); const result = await s.workflows.search(s.identity, { query: 'Payment', types: ['doc'] }); const fetched = await s.workflows.fetch(s.identity, { result_id: result.results[0]!.result_id, max_chars: 20 }); expect(fetched.truncated).toBe(true); expect(fetched.content_trust).toBe('untrusted_source_data'); await expect(s.workflows.fetch(demoIdentity('beta'), { result_id: result.results[0]!.result_id })).rejects.toThrow('different'); });
  it('invalidates a content cursor if the document changed between fetches', async () => { const s = setup(); const found = await s.workflows.search(s.identity, { query: 'Payment', types: ['doc'] }); const ref = found.results[0]!.result_id; const page = await s.workflows.fetch(s.identity, { result_id: ref, max_chars: 20 }); s.request.mockResolvedValueOnce({ code: 0, data: { document: { document_id: 'doc_fixture', title: 'Changed' } } }).mockResolvedValueOnce({ code: 0, data: { content: 'Completely changed document contents.' } }); await expect(s.workflows.fetch(s.identity, { result_id: ref, max_chars: 20, cursor: page.next_cursor! })).rejects.toThrow('Cursor'); });
  it('resolves Wiki nodes to their actual DOCX object before fetching', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { res_units: [{ entity_type: 'WIKI', result_meta: { token: 'wiki_fixture', doc_types: 'DOCX' } }], has_more: false } }); const search = await s.workflows.search(s.identity, { query: 'Demo', types: ['wiki'] }); expect(search.results[0]!.type).toBe('wiki'); const result = await s.workflows.fetch(s.identity, { result_id: search.results[0]!.result_id }); expect(result.content).toContain('provider fixture'); expect(s.request.mock.calls[1]![0].params).toMatchObject({ token: 'wiki_fixture', obj_type: 'wiki' }); });
  it('does not fetch unsupported Wiki spreadsheets as documents', async () => { const s = setup(); const ref = s.handles.encode('resource', s.identity, { provider: 'feishu', kind: 'wiki', id: 'wiki_fixture' }); s.request.mockResolvedValueOnce({ code: 0, data: { node: { obj_type: 'sheet', obj_token: 'sheet_fixture', node_type: 'origin' } } }); await expect(s.workflows.fetch(s.identity, { result_id: ref })).rejects.toThrow('not a readable'); expect(s.request).toHaveBeenCalledTimes(1); });
  it('reads message text using the actual message ID and content JSON schema', async () => { const s = setup(); const found = await s.workflows.search(s.identity, { query: 'Payment', types: ['message'] }); const fetched = await s.workflows.fetch(s.identity, { result_id: found.results[0]!.result_id }); expect(fetched.content).toBe('Message content stays source data.'); expect(fetched.next_cursor).toBeNull(); });
  it('does not turn arbitrary URLs into fetches', async () => { const s = setup(); await expect(s.workflows.fetch(s.identity, { result_id: 'https://attacker.example/private' })).rejects.toThrow(); expect(s.request).not.toHaveBeenCalled(); });
  it('does not leak message results outside an explicit chat filter', async () => { const s = setup(); await expect(s.reads.searchMessages(s.identity, { query: 'Payment', chat_id: 'different_chat' })).rejects.toThrow('outside'); });
  it('marks a partial reply set as partial even when the comment list has ended', async () => { const s = setup(); const result = await s.workflows.comments(s.identity, 'doc_fixture'); expect(result.partial).toBe(true); expect(result.next_cursor).toBeNull(); expect(result.comments[0]!.replies_complete).toBe(false); expect(s.request.mock.calls[0]![0].params.file_type).toBe('docx'); });
  it('gets the authoritative thread ID from the requested message then pages its replies', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { items: [{ message_id: 'om_fixture', chat_id: 'oc_fixture', thread_id: 'omt_fixture', msg_type: 'text', body: { content: '{"text":"Root"}' } }] } }).mockResolvedValueOnce({ code: 0, data: { items: [{ message_id: 'om_reply', chat_id: 'oc_fixture', thread_id: 'omt_fixture', msg_type: 'text', body: { content: '{"text":"Reply"}' } }], has_more: false } }); const result = await s.workflows.messageThread(s.identity, 'om_fixture'); expect(result.messages[0]!.content).toBe('Reply'); expect(result.coverage).toBe('thread_messages'); expect(s.request.mock.calls[1]![0]).toMatchObject({ url: 'https://open.feishu.cn/open-apis/im/v1/messages', method: 'GET', params: { container_id_type: 'thread', container_id: 'omt_fixture' } }); });
  it('never expands an unthreaded message into an unrelated chat history', async () => { const s = setup(); const result = await s.workflows.messageThread(s.identity, 'om_fixture'); expect(result.coverage).toBe('standalone_message'); expect(s.request).toHaveBeenCalledTimes(1); });
  it('does not represent an unavailable message body as a real empty message', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { items: [{ message_id: 'om_fixture' }] } }); await expect(s.workflows.messageThread(s.identity, 'om_fixture')).rejects.toThrow('message body'); });
  it('rejects a provider reply from a different thread', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { items: [{ message_id: 'om_fixture', chat_id: 'oc_fixture', thread_id: 'omt_fixture' }] } }).mockResolvedValueOnce({ code: 0, data: { items: [{ message_id: 'om_other', chat_id: 'oc_fixture', thread_id: 'omt_other' }], has_more: false } }); await expect(s.workflows.messageThread(s.identity, 'om_fixture')).rejects.toThrow('outside'); });
  it('suggests only explicit-window slots avoiding known busy intervals', async () => { const s = setup(); const result = await s.workflows.suggestMeetingTimes(s.identity, { people: ['ou_fixture'], time_range: { start: '2026-10-05T08:00:00Z', end: '2026-10-05T11:00:00Z' }, timezone: 'Asia/Shanghai', duration_minutes: 60, limit: 5 }); expect(result.slots).toHaveLength(2); expect(result.slots.map(slot => slot.start)).toEqual(['2026-10-05T08:00:00.000Z', '2026-10-05T10:00:00.000Z']); expect(result.slots[0]!.local_start).toContain('16:00'); expect(result.action_taken).toBe(false); });
  it('does not recommend meeting slots from missing or malformed availability', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { freebusy_lists: [{ user_id: 'ou_fixture' }] } }); await expect(s.workflows.suggestMeetingTimes(s.identity, { people: ['ou_fixture'], time_range: { start: '2026-10-05T08:00:00Z', end: '2026-10-05T11:00:00Z' }, timezone: 'UTC', duration_minutes: 30 })).rejects.toThrow('unknown'); });
});
