import { describe, expect, it, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { FeishuProviderDomains } from '../packages/feishu/src/provider-domains.js';
import { FeishuSdkReadGateway, bindSdkReads } from '../packages/feishu/src/sdk-reads.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';
import { PostgresConnectionRepository } from '../packages/auth/src/connection-repository.js';
import { TokenCipher } from '../packages/auth/src/vault.js';
import { assertProviderGrant } from '../packages/feishu/src/provider-scope-evidence.js';

const fields = [{ field_id: 'fld_title', field_name: 'Title', type: 1 }, { field_id: 'fld_score', field_name: 'Score', type: 2 }];
const range = { start: '2026-10-05T00:00:00Z', end: '2026-10-06T00:00:00Z' };
function setup() {
  const request = vi.fn().mockImplementation(async config => config.url.endsWith('/fields') ? { code: 0, data: { items: fields, has_more: false } } : { code: 0, data: { items: [{ record_id: 'rec_fixture', fields: { Title: 'Demo', Score: 7 } }], has_more: false } });
  const identity = demoIdentity();
  const client = createSafeSdkClient({ appId: 'synthetic', appSecret: 'synthetic', domain: 'feishu', httpInstance: { request } as never });
  const gateway = new FeishuSdkReadGateway({ identity, reads: bindSdkReads(client) }, { get: async () => ({ accessToken: 'synthetic', refreshToken: 'synthetic', expiresAt: Date.now() + 1_000_000, refreshExpiresAt: Date.now() + 2_000_000 }) });
  return { request, identity, gateway, domains: new FeishuProviderDomains(gateway, new Handles(randomBytes(32))) };
}
describe('targeted Base and calendar provider mappings', () => {
  it('resolves real field IDs to provider field names and string filter arrays', async () => { const s = setup(); const result = await s.domains.queryBase(s.identity, { base_id: 'app_fixture', table_id: 'tbl_fixture', fields: ['fld_score'], filter: { field_id: 'fld_score', operator: 'gt', value: 3 }, sort: { field_id: 'fld_score', direction: 'desc' } }); expect(s.request.mock.calls[1]![0].data).toEqual({ field_names: ['Score'], filter: { conjunction: 'and', conditions: [{ field_name: 'Score', operator: 'isGreater', value: ['3'] }] }, sort: [{ field_name: 'Score', desc: true }] }); expect(result.records[0]!.fields).toEqual({ fld_score: { name: 'Score', provider_type: 2, value: 7 } }); });
  it('rejects invented field IDs before the records API', async () => { const s = setup(); await expect(s.domains.queryBase(s.identity, { base_id: 'app_fixture', table_id: 'tbl_fixture', fields: ['invented'] })).rejects.toThrow('Unknown'); expect(s.request).toHaveBeenCalledTimes(1); });
  it('rejects type-incompatible filters', async () => { const s = setup(); await expect(s.domains.queryBase(s.identity, { base_id: 'app_fixture', table_id: 'tbl_fixture', filter: { field_id: 'fld_score', operator: 'contains', value: 3 } })).rejects.toThrow('match'); expect(s.request).toHaveBeenCalledTimes(1); });
  it('retrieves every schema page before translating fields', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { items: [fields[0]], has_more: true, page_token: 'page-two' } }).mockResolvedValueOnce({ code: 0, data: { items: [fields[1]], has_more: false } }); const schema = await s.domains.baseSchema(s.identity, 'app_fixture', 'tbl_fixture'); expect(schema.fields).toHaveLength(2); expect(s.request.mock.calls[1]![0].params.page_token).toBe('page-two'); });
  it('blocks provider pagination cycles and ambiguous schema names', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { items: [], has_more: true, page_token: 'same' } }); await expect(s.domains.baseSchema(s.identity, 'app', 'table')).rejects.toThrow('repeated'); expect(s.request).toHaveBeenCalledTimes(2); s.request.mockResolvedValue({ code: 0, data: { items: [fields[0], { ...fields[0], field_id: 'another' }], has_more: false } }); await expect(s.domains.baseSchema(s.identity, 'app', 'table')).rejects.toThrow('ambiguous'); });
  it('rejects path traversal and injected headers before acquiring a provider token', async () => { const s = setup(); await expect(s.gateway.call('readDocument', { path: { document_id: '../oauth/token' } }, s.identity)).rejects.toThrow('ID'); await expect(s.gateway.call('profile', { headers: { Authorization: 'bad' } } as never, s.identity)).rejects.toThrow('shape'); expect(s.request).not.toHaveBeenCalled(); });
  it.each(['.', '..'])('rejects a standalone dot-segment resource ID %s', async value => { const s = setup(); await expect(s.gateway.call('readDocument', { path: { document_id: value } }, s.identity)).rejects.toThrow('ID'); expect(s.request).not.toHaveBeenCalled(); });
  it('uses calendar_list rather than inventing items and drops deleted calendars', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { calendar_list: [{ calendar_id: 'cal-active', summary: 'Work', type: 'primary' }, { calendar_id: 'cal-deleted', is_deleted: true }], has_more: false } }); const result = await s.domains.calendars(s.identity); expect(result.calendars).toHaveLength(1); expect(result.calendars[0]!.calendar_id).toBe('cal-active'); });
  it('retains all-day date semantics rather than fabricating midnight UTC', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { items: [{ event_id: 'evt', summary: 'Day', start_time: { date: '2026-10-05' }, end_time: { date: '2026-10-06' } }], has_more: false } }); const result = await s.domains.agenda(s.identity, { calendar_id: 'feishu.cn_demo@group.calendar.feishu.cn', time_range: range, timezone: 'Asia/Shanghai' }); expect(result.events[0]!.start).toEqual({ date: '2026-10-05' }); expect(result.time_encoding).toBe('provider_timestamp_or_all_day_date'); });
  it('does not treat missing free/busy information as an empty calendar', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { freebusy_lists: [{ user_id: 'ou_1', freebusy_items: [] }] } }); const result = await s.domains.freeBusy(s.identity, { people: ['ou_1', 'ou_2'], time_range: range, timezone: 'Asia/Shanghai' }); expect(result.complete).toBe(false); expect(result.unknown_people).toEqual(['ou_2']); expect(result.people[1]!.known).toBe(false); });
  it('marks malformed busy intervals unknown rather than claiming availability', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { freebusy_lists: [{ user_id: 'ou_1', freebusy_items: [{ start_time: 'invalid', end_time: 'invalid' }] }] } }); const result = await s.domains.freeBusy(s.identity, { people: ['ou_1'], time_range: range, timezone: 'UTC' }); expect(result.complete).toBe(false); expect(result.people[0]!.known).toBe(false); expect(result.people[0]!.busy).toEqual([]); });
  it('sends RFC3339 time_min/time_max to the real freebusy batch contract', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { freebusy_lists: [{ user_id: 'ou_1', freebusy_items: [] }] } }); await s.domains.freeBusy(s.identity, { people: ['ou_1'], time_range: range, timezone: 'Asia/Shanghai' }); expect(s.request.mock.calls[0]![0].data).toMatchObject({ time_min: range.start, time_max: range.end, user_ids: ['ou_1'], include_external_calendar: true }); });
  it('does not claim room availability from room-search metadata', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { rooms: [{ room_id: 'room1', name: 'A', capacity: 8 }], has_more: false } }); const result = await s.domains.rooms(s.identity, 'A'); expect(result.rooms[0]!.availability).toBe('not_queried'); expect(s.request.mock.calls[0]![0].data.keyword).toBe('A'); });
  it('checks room busy through the real single-room endpoint without any user_id', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { freebusy_list: [] } }); const result = await s.domains.roomAvailability(s.identity, 'room1', range); expect(result.available).toBe(true); expect(s.request.mock.calls[0]![0]).toMatchObject({ url: 'https://open.feishu.cn/open-apis/calendar/v4/freebusy/list', data: { room_id: 'room1', time_min: range.start, time_max: range.end } }); expect(s.request.mock.calls[0]![0].data).not.toHaveProperty('user_id'); });
  it('does not turn missing room freebusy_list into available', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: {} }); const result = await s.domains.roomAvailability(s.identity, 'room1', range); expect(result.known).toBe(false); expect(result.available).toBeNull(); });
  it('does not accept numeric room timestamps as valid RFC3339 intervals', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { freebusy_list: [{ start_time: 0, end_time: 1 }] } }); expect((await s.domains.roomAvailability(s.identity, 'room1', range)).known).toBe(false); });
  it('combines room capacity and busy checks without claiming that unknown rooms fit', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { rooms: [{ room_id: 'room1', name: 'A', capacity: 8 }, { room_id: 'room2', name: 'Unknown capacity' }, { room_id: 'room3', name: 'Too small', capacity: 2 }], has_more: false } }).mockResolvedValueOnce({ code: 0, data: { freebusy_list: [{ start_time: range.start, end_time: range.end }] } }); const result = await s.domains.roomsWithAvailability(s.identity, { min_capacity: 6, time_range: range }); expect(result.rooms).toHaveLength(1); expect(result.rooms[0]!.available).toBe(false); expect(result.rooms[0]).not.toHaveProperty('availability'); expect(result.capacity_unknown_excluded).toBe(1); expect(s.request).toHaveBeenCalledTimes(2); });
  it('preserves room availability failures as unknown and partial with no raw provider error', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { rooms: [{ room_id: 'room1', name: 'A', capacity: 8 }], has_more: false } }).mockRejectedValueOnce({ response: { status: 403, data: 'private error details' } }); const result = await s.domains.roomsWithAvailability(s.identity, { time_range: range }); expect(result.partial).toBe(true); expect(result.rooms[0]!.available).toBeNull(); expect(JSON.stringify(result)).not.toContain('private error details'); });
  it('binds a room continuation to its exact window and capacity filter', async () => { const s = setup(); s.request.mockResolvedValueOnce({ code: 0, data: { rooms: [], has_more: true, page_token: 'room-page2' } }); const result = await s.domains.roomsWithAvailability(s.identity, { min_capacity: 8, time_range: range }); await expect(s.domains.roomsWithAvailability(s.identity, { min_capacity: 4, time_range: range, cursor: result.next_cursor! })).rejects.toThrow('filters'); expect(s.request).toHaveBeenCalledTimes(1); });
  it('rejects room pagination token cycles without repeatedly querying availability', async () => { const s = setup(); s.request.mockResolvedValue({ code: 0, data: { rooms: [], has_more: true, page_token: 'repeated-room-page' } }); const first = await s.domains.rooms(s.identity, undefined); await expect(s.domains.rooms(s.identity, undefined, { cursor: first.next_cursor! })).rejects.toThrow('repeated'); });
  it('does not mistake internal scopes or verified documentation for actual Feishu consent', () => { expect(() => assertProviderGrant('searchPeople', ['people.read'])).toThrow('actual'); expect(() => assertProviderGrant('searchPeople', [])).toThrow(); expect(() => assertProviderGrant('searchPeople', ['contact:user:search'])).not.toThrow(); expect(() => assertProviderGrant('unknown' as never, ['contact:user:search'])).toThrow('not been verified'); });
});

describe('PostgreSQL connection-link transaction contracts', () => {
  function db() { const query = vi.fn().mockResolvedValue({ rows: [], rowCount: 1 }); const release = vi.fn(); const connect = vi.fn().mockResolvedValue({ query, release }); const cipher = new TokenCipher(new Map([['v1', randomBytes(32)]]), 'v1'); return { query, release, connect, repository: new PostgresConnectionRepository({ connect } as never, cipher) }; }
  const identity = demoIdentity();
  const tokens = { accessToken: 'synthetic-access', refreshToken: 'synthetic-refresh', expiresAt: 1_000_000, refreshExpiresAt: 2_000_000 };
  it('commits a verified identity and encrypted tokens atomically', async () => { const s = db(); await s.repository.link(identity, { openId: 'ou_fixture', tenantId: identity.tenantId }, tokens); const commands = s.query.mock.calls.map(call => String(call[0])); expect(commands[0]).toBe('BEGIN'); expect(commands.at(-1)).toBe('COMMIT'); expect(JSON.stringify(s.query.mock.calls).includes(tokens.accessToken)).toBe(false); expect(s.release).toHaveBeenCalledTimes(1); });
  it('rolls back a conflicting owner without overwriting token data', async () => { const s = db(); s.query.mockResolvedValueOnce({ rows: [], rowCount: 0 }).mockResolvedValueOnce({ rows: [], rowCount: 0 }); await expect(s.repository.link(identity, { openId: 'ou_fixture', tenantId: identity.tenantId }, tokens)).rejects.toThrow('another'); expect(s.query.mock.calls.at(-1)![0]).toBe('ROLLBACK'); expect(s.query.mock.calls.some(call => String(call[0]).includes('INSERT INTO feishu_tokens'))).toBe(false); expect(s.release).toHaveBeenCalledTimes(1); });
  it('sanitizes database failures and rolls back', async () => { const s = db(); s.query.mockResolvedValueOnce({ rows: [], rowCount: 0 }).mockRejectedValueOnce(new Error('sensitive query contents')); await expect(s.repository.link(identity, { openId: 'ou_fixture', tenantId: identity.tenantId }, tokens)).rejects.toThrow('could not be saved'); expect(s.query.mock.calls.at(-1)![0]).toBe('ROLLBACK'); expect(s.release).toHaveBeenCalledTimes(1); });
  it('revokes local connection, stored credentials and MCP grants in one transaction', async () => { const s = db(); await s.repository.disconnect(identity); const sql = s.query.mock.calls.map(call => String(call[0])).join('\n'); expect(sql).toContain("status='revoked'"); expect(sql).toContain('DELETE FROM feishu_tokens'); expect(sql).toContain('UPDATE oauth_grants SET revoked_at'); expect(s.query.mock.calls.at(-1)![0]).toBe('COMMIT'); });
});
