import { describe, expect, it, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { FeishuProviderTasks } from '../packages/feishu/src/provider-tasks.js';
import { FeishuSdkReadGateway, bindSdkReads } from '../packages/feishu/src/sdk-reads.js';
import { createSafeSdkClient } from '../packages/feishu/src/sdk-client.js';
import { demoIdentity } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';

const task = (guid = 'task1', assignee = 'ou_person') => ({ guid, summary: 'Synthetic task', completed_at: '0', members: [{ id: assignee, type: 'user', role: 'assignee' }] });
function setup() {
  const request = vi.fn(); const get = vi.fn().mockResolvedValue({ accessToken: 'synthetic', refreshToken: 'synthetic', expiresAt: Date.now()+1e6, refreshExpiresAt: Date.now()+2e6 });
  const identity=demoIdentity(); const handles=new Handles(randomBytes(32));
  const client=createSafeSdkClient({appId:'fixture',appSecret:'fixture',domain:'feishu',httpInstance:{request} as never});
  const gateway=new FeishuSdkReadGateway({identity,reads:bindSdkReads(client)},{get},async()=>{});
  return { identity, request, get, tasks:new FeishuProviderTasks(gateway,handles) };
}
describe('tasklist and explicit assignee workflows',()=>{
  it('does not represent unknown member roles as a verified empty assignee list',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{task:{...task(),members:[{id:'ou_person'}]}}});expect((await s.tasks.detail(s.identity,'task1')).assignee_open_ids).toBeNull()});
  it('rejects a malformed search coverage notice before enriching details',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[{id:'task1'}],has_more:false,notice:{message:'unknown'}}});await expect(s.tasks.list(s.identity,{assignee_id:'ou_person'})).rejects.toThrow('notice');expect(s.request).toHaveBeenCalledTimes(1)});
  it('lists visible tasklists with user identity and only projected fields',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[{guid:'list1',name:'Fixture list',private_data:'not projected'}],has_more:false}});const result=await s.tasks.tasklists(s.identity);expect(result.tasklists).toEqual([{tasklist_id:'list1',name:'Fixture list'}]);expect(s.request.mock.calls[0]![0]).toMatchObject({method:'GET',url:'https://open.feishu.cn/open-apis/task/v2/tasklists',params:{user_id_type:'open_id',page_size:20}});expect(s.request.mock.calls[0]![0].headers.Authorization==='Bearer synthetic').toBe(true)});
  it('uses tasklist_guid and preserves empty nonterminal pages',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:'next'}}).mockResolvedValueOnce({code:0,data:{items:[task()],has_more:false}});const first=await s.tasks.list(s.identity,{tasklist_id:'list1'});expect(first.tasks).toEqual([]);expect(first.next_cursor).not.toBeNull();const next=await s.tasks.list(s.identity,{tasklist_id:'list1'},{cursor:first.next_cursor!});expect(next.tasks[0]!.task_id).toBe('task1');expect(next.coverage).toBe('tasks_in_requested_list');expect(s.request.mock.calls[1]![0]).toMatchObject({method:'GET',url:'https://open.feishu.cn/open-apis/task/v2/tasklists/list1/tasks',params:{page_token:'next',user_id_type:'open_id'}})});
  it('does not send an invented assignee filter to the tasklist endpoint',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[task(),task('other','ou_other')],has_more:false}});const result=await s.tasks.list(s.identity,{tasklist_id:'list1',assignee_id:'ou_person'});expect(result.tasks.map(item=>item.task_id)).toEqual(['task1']);expect(result.omitted).toEqual([{task_id:'other',reason:'filter_mismatch'}]);expect(s.request.mock.calls[0]![0].params).not.toHaveProperty('assignee_id');expect(s.request.mock.calls[0]![0].data).toEqual({});expect(result.partial).toBe(true)});
  it('uses POST search with assignee_ids then exact task detail reads',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{id:'task1'}],has_more:false}}).mockResolvedValueOnce({code:0,data:{task:task()}});const result=await s.tasks.list(s.identity,{assignee_id:'ou_person',status:'todo'});expect(result.tasks).toHaveLength(1);expect(result.coverage).toBe('visible_tasks_for_explicit_assignee');expect(s.request.mock.calls[0]![0]).toMatchObject({method:'POST',url:'https://open.feishu.cn/open-apis/task/v2/tasks/search',data:{query:'',filter:{assignee_ids:['ou_person'],is_completed:false}},params:{page_size:20,user_id_type:'open_id'}});expect(s.request.mock.calls[1]![0]).toMatchObject({method:'GET',url:'https://open.feishu.cn/open-apis/task/v2/tasks/task1',params:{user_id_type:'open_id'}});expect(s.request.mock.calls.every(call=>call[0].headers.Authorization==='Bearer synthetic')).toBe(true)});
  it('puts search page_token in the query, not the body',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:'next'}}).mockResolvedValueOnce({code:0,data:{items:[],has_more:false}});const first=await s.tasks.list(s.identity,{assignee_id:'ou_person'});await s.tasks.list(s.identity,{assignee_id:'ou_person'},{cursor:first.next_cursor!});expect(s.request.mock.calls[1]![0].params.page_token).toBe('next');expect(s.request.mock.calls[1]![0].data).not.toHaveProperty('page_token')});
  it('never labels my_tasks as an arbitrary assignee search',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[task()],has_more:false}});const result=await s.tasks.list(s.identity,{});expect(result.coverage).toBe('tasks_assigned_to_current_user');expect(s.request.mock.calls[0]![0]).toMatchObject({url:'https://open.feishu.cn/open-apis/task/v2/tasks',method:'GET',params:{type:'my_tasks'}});expect(s.request.mock.calls[0]![0].params).not.toHaveProperty('completed')});
  it('reports inaccessible task detail as partial, preserving later results',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{id:'gone'},{id:'task1'}],has_more:false}}).mockRejectedValueOnce({response:{status:403}}).mockResolvedValueOnce({code:0,data:{task:task()}});const result=await s.tasks.list(s.identity,{assignee_id:'ou_person'});expect(result.tasks).toHaveLength(1);expect(result.omitted).toEqual([{task_id:'gone',reason:'PERMISSION_DENIED'}]);expect(result.partial).toBe(true)});
  it('stops on required reauthorization instead of treating it as an empty task search',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{id:'task1'}],has_more:false}}).mockRejectedValueOnce({response:{status:401}});await expect(s.tasks.list(s.identity,{assignee_id:'ou_person'})).rejects.toThrow('authorization')});
  it.each([{...task(),members:undefined},{...task(),members:[{id:'ou_person'}]},{...task(),members:[{id:'ou_person',type:'user',role:'follower'}]},{...task(),members:[{id:'ou_person',type:'app',role:'assignee'}]},task('task1','ou_other')])('never passes unverified assignee matches: %s',async detail=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{id:'task1'}],has_more:false}}).mockResolvedValueOnce({code:0,data:{task:detail}});const result=await s.tasks.list(s.identity,{assignee_id:'ou_person'});expect(result.tasks).toEqual([]);expect(result.partial).toBe(true);expect(result.omitted).toHaveLength(1)});
  it('never returns task content from a mismatched detail ID',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{id:'task1'}],has_more:false}}).mockResolvedValueOnce({code:0,data:{task:task('other')}});const result=await s.tasks.list(s.identity,{assignee_id:'ou_person'});expect(result.tasks).toEqual([]);expect(result.omitted).toEqual([{task_id:'task1',reason:'UPSTREAM_ERROR'}])});
  it.each([undefined,'2000000'])('does not claim missing or mismatched completion %s matches todo',async completed_at=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[{...task(),completed_at}],has_more:false}});const result=await s.tasks.list(s.identity,{status:'todo'});expect(result.tasks).toEqual([]);expect(result.partial).toBe(true)});
  it('preserves unknown completion and all-day due semantics when not filtering status',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{task:{...task(),completed_at:undefined,due:{timestamp:'1791244800000',is_all_day:true}}}});const result=await s.tasks.detail(s.identity,'task1');expect(result.completed).toBeNull();expect(result.due).toEqual({timestamp:'1791244800000',is_all_day:true})});
  it('enforces detail fan-out limits before transport, even when provider over-returns',async()=>{const s=setup();await expect(s.tasks.list(s.identity,{assignee_id:'ou_person'},{page_size:21})).rejects.toThrow('twenty');expect(s.request).not.toHaveBeenCalled();s.request.mockResolvedValue({code:0,data:{items:Array.from({length:21},(_,i)=>({id:'t'+i})),has_more:false}});await expect(s.tasks.list(s.identity,{assignee_id:'ou_person'})).rejects.toThrow('oversized');expect(s.request).toHaveBeenCalledTimes(1)});
  it('retains provider truncation notices as partial rather than claiming complete coverage',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[],has_more:false,notice:'Please narrow query'}});const result=await s.tasks.list(s.identity,{assignee_id:'ou_person'});expect(result.partial).toBe(true);expect(result.notice).toBe('Please narrow query')});
  it.each([{},{items:[]},{items:[],has_more:true},{items:[task(),task()],has_more:false}])('rejects incomplete task-list data %s',async data=>{const s=setup();s.request.mockResolvedValue({code:0,data});await expect(s.tasks.list(s.identity,{tasklist_id:'list1'})).rejects.toThrow()});
  it('binds task cursors to query, page size, identity and scopes',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{items:[],has_more:true,page_token:'next'}});const first=await s.tasks.list(s.identity,{tasklist_id:'list1'});const cursor=first.next_cursor!;for(const [identity,query,page] of [[s.identity,{tasklist_id:'other'},{cursor}],[s.identity,{tasklist_id:'list1',status:'done'},{cursor}],[s.identity,{tasklist_id:'list1'},{cursor,page_size:10}],[demoIdentity('beta'),{tasklist_id:'list1'},{cursor}],[{...s.identity,scopes:['task.read']},{tasklist_id:'list1'},{cursor}]] as const)await expect(s.tasks.list(identity,query,page)).rejects.toThrow();expect(s.request).toHaveBeenCalledTimes(1)});
  it('rejects A-B-A task pagination cycles',async()=>{const s=setup();for(const token of ['A','B','A'])s.request.mockResolvedValueOnce({code:0,data:{items:[],has_more:true,page_token:token}});const a=await s.tasks.list(s.identity,{});const b=await s.tasks.list(s.identity,{}, {cursor:a.next_cursor!});await expect(s.tasks.list(s.identity,{}, {cursor:b.next_cursor!})).rejects.toThrow('repeated')});
  it('blocks reads without task scope and rejects same-tenant session swaps',async()=>{const s=setup();await expect(s.tasks.list({...s.identity,scopes:[]},{})).rejects.toThrow('permission');await expect(s.tasks.tasklists(demoIdentity('beta'))).rejects.toThrow('different');expect(s.get).not.toHaveBeenCalled();expect(s.request).not.toHaveBeenCalled()});
});
