import { beforeAll,beforeEach,afterAll,describe,it,expect,vi } from 'vitest';
import { createTaskReviewFixture,input,bearer,created,tokenData,identity } from './helpers/task-review-fixture.js';
import { CreateTaskWorkflow } from '../packages/tools/src/create-task-workflow.js';
import { PostgresTaskWriteStore } from '../packages/policy/src/task-write-store.js';
import { PostgresDocumentWriteAccess } from '../packages/auth/src/document-write-access.js';
import { writeBinding } from '../packages/schemas/src/document-write.js';
import { taskBinding } from '../packages/schemas/src/task-write.js';
const transport=vi.fn();let f:Awaited<ReturnType<typeof createTaskReviewFixture>>;
beforeAll(async()=>{f=await createTaskReviewFixture(transport);},30000);beforeEach(async()=>{await f.reset();transport.mockReset();transport.mockResolvedValue(created);});afterAll(async()=>{await f.close();});
async function approve(key='task_fixture',raw:unknown=input){const p=await f.w.preview(bearer,raw,key),proof=f.authority.issue({...p.confirmation_request,decision:'approve'});await f.w.confirm(bearer,p.receipt.intent_id,proof);return p;}
describe('durable task preview/confirmation/execution',()=>{
 it('previews full content/deadline and unassigned scope without storing private bodies or reading provider',async()=>{const p=await f.w.preview(bearer,input,'preview_fixture');expect(p.review).toMatchObject({...input,assignment:'unassigned',tasklists:[],reminders:'not_configured'});const rows=JSON.stringify((await f.query('SELECT * FROM task_write_intents')).rows);for(const value of [input.summary,input.description,input.due.at,bearer,tokenData.accessToken,'preview_fixture'])expect(rows).not.toContain(value);expect(transport).not.toHaveBeenCalled();});
 it('accepts absent deadline and description as an explicit minimal task',async()=>{const p=await approve('minimal_fixture',{summary:'Minimal'});expect(p.review).not.toHaveProperty('due');await f.w.execute(bearer,p.receipt.intent_id,{summary:'Minimal'});expect(transport.mock.calls[0]![0].data).not.toHaveProperty('due');});
 it('requires a server-confirmed proof, dispatches once and records a body-free receipt',async()=>{const p=await approve();expect(transport).not.toHaveBeenCalled();const r=await f.w.execute(bearer,p.receipt.intent_id,input);expect(r).toMatchObject({operation:'create_task',status:'succeeded',task_guid:created.data.task.guid,read_back_verified:false,live_verified:false,automatic_create_retry_allowed:false});expect(transport.mock.calls[0]![0].data.client_token).toBe(p.receipt.intent_id);expect((await f.w.execute(bearer,p.receipt.intent_id,input)).replayed).toBe(true);expect(transport).toHaveBeenCalledTimes(1);expect(JSON.stringify((await f.query('SELECT receipt FROM task_write_intents')).rows)).not.toContain(input.description);});
 it('never executes an unconfirmed task and does not accept approved client properties',async()=>{const p=await f.w.preview(bearer,input,'unconfirmed');await expect(f.w.execute(bearer,p.receipt.intent_id,input)).rejects.toMatchObject({type:'PERMISSION_DENIED'});await expect(f.w.preview(bearer,{...input,approved:true},'bad_prop')).rejects.toThrow();expect(transport).not.toHaveBeenCalled();});
 it('task and document operation bindings cannot authorize each other',async()=>{const principal=await f.access.authenticate(bearer);expect(taskBinding(principal)).not.toBe(writeBinding(principal));const p=await f.w.preview(bearer,input,'cross_proof');const proof=f.authority.issue({...p.confirmation_request,binding:writeBinding(principal),decision:'approve'});await expect(f.w.confirm(bearer,p.receipt.intent_id,proof)).rejects.toThrow();await expect(new PostgresDocumentWriteAccess({query:f.query} as never,f.tokens,'https://mcp.example.test/mcp').authenticate(bearer)).rejects.toMatchObject({type:'INSUFFICIENT_SCOPE'});expect(transport).not.toHaveBeenCalled();});
 it.each([{summary:'Changed'},{description:'Changed'},{due:{kind:'all_day',date:'2026-10-10'}},{due:undefined}])('rejects task/deadline changes after approval %j',async change=>{const p=await approve();await expect(f.w.execute(bearer,p.receipt.intent_id,{...input,...change})).rejects.toMatchObject({type:'CONFLICT'});expect(transport).not.toHaveBeenCalled();});
 it('same key deduplicates exact task and conflicts on a different deadline/content',async()=>{const p=await approve();await f.w.execute(bearer,p.receipt.intent_id,input);expect((await f.w.preview(bearer,input,'task_fixture')).receipt.intent_id).toBe(p.receipt.intent_id);await expect(f.w.preview(bearer,{...input,description:'Other'},'task_fixture')).rejects.toMatchObject({type:'CONFLICT'});expect(transport).toHaveBeenCalledTimes(1);});
 it('cancelled and expired previews never create tasks',async()=>{const p=await f.w.preview(bearer,input,'cancel_fixture');await f.w.confirm(bearer,p.receipt.intent_id,f.authority.issue({...p.confirmation_request,decision:'cancel'}));expect((await f.w.execute(bearer,p.receipt.intent_id,input)).status).toBe('cancelled');const q=await approve('expired_fixture');await f.query("UPDATE task_write_intents SET expires_at=now()-interval '1 second' WHERE id=$1",[q.receipt.intent_id]);expect((await f.w.execute(bearer,q.receipt.intent_id,input)).status).toBe('expired');expect(transport).not.toHaveBeenCalled();});
 it('simultaneous executions reserve one POST',async()=>{const p=await approve();await Promise.all(Array.from({length:6},()=>f.w.execute(bearer,p.receipt.intent_id,input)));expect(transport).toHaveBeenCalledTimes(1);});
 it('an executing reservation survives process recreation and provider dedupe-window expiry',async()=>{const p=await approve(),principal=await f.access.authenticate(bearer);await f.store.claim(principal,p.receipt.intent_id);await f.query("UPDATE task_write_intents SET updated_at=now()-interval '1 day',expires_at=now()-interval '23 hours'");const restarted=new PostgresTaskWriteStore({query:f.query} as never);expect(await restarted.claim(principal,p.receipt.intent_id)).toBe(false);expect((await f.w.execute(bearer,p.receipt.intent_id,input)).status).toBe('executing');expect(transport).not.toHaveBeenCalled();});
 it('ambiguous failure consumes the operation permanently; status never retries provider or refreshes tokens',async()=>{transport.mockRejectedValue(new Error('private provider failure'));const p=await approve();expect((await f.w.execute(bearer,p.receipt.intent_id,input)).status).toBe('uncertain');await f.query("UPDATE task_write_intents SET updated_at=now()-interval '1 day',expires_at=now()-interval '23 hours'");expect((await f.w.execute(bearer,p.receipt.intent_id,input)).status).toBe('uncertain');await f.w.getReceipt(bearer,p.receipt.intent_id,true);expect(transport).toHaveBeenCalledTimes(1);});
 it('known task with incomplete or mismatched result remains partial without corrective writes',async()=>{transport.mockResolvedValue({code:0,data:{task:{...created.data.task,description:'different'}}});const p=await approve();expect(await f.w.execute(bearer,p.receipt.intent_id,input)).toMatchObject({status:'partial',task_guid:created.data.task.guid,unverified_fields:['description'],response_fields_verified:false});await f.w.getReceipt(bearer,p.receipt.intent_id,true);expect(transport).toHaveBeenCalledTimes(1);});
 it('receipt-store failure after provider success retains executing reservation',async()=>{const p=await approve(),store=new PostgresTaskWriteStore({query:async(sql:string,values:unknown[])=>{if(sql.includes('receipt=$2::jsonb'))throw new Error('synthetic persistence failure');return f.query(sql,values);}} as never);const w=new CreateTaskWorkflow(f.access,store,f.authority,()=>({domain:'feishu',create:async()=>{transport();return{status:'succeeded',guid:created.data.task.guid,url:null,unverified:[]};}} as never),{enabled:true});await expect(w.execute(bearer,p.receipt.intent_id,input)).rejects.toMatchObject({type:'UPSTREAM_ERROR'});expect((await f.w.execute(bearer,p.receipt.intent_id,input)).status).toBe('executing');expect(transport).toHaveBeenCalledTimes(1);});
 it.each(['task:task:write','task:task:writeonly'])('accepts the documented granted permission alternative %s',async scope=>{await f.query('UPDATE feishu_connections SET provider_scopes=$1',[[scope]]);expect((await f.w.preview(bearer,input,'scope_fixture')).requires_confirmation).toBe(true);});
 it.each([{scopes:['task:task:read']},{scopes:['task.write']},{scopes:['docx:document:create']},{scopes:[]}])('rejects insufficient actual provider grant %j',async({scopes})=>{await f.query('UPDATE feishu_connections SET provider_scopes=$1',[scopes]);await expect(f.w.preview(bearer,input,'scope_fixture')).rejects.toMatchObject({type:'PERMISSION_DENIED'});expect(transport).not.toHaveBeenCalled();});
 it('default-off workflow never authenticates or dispatches',async()=>{const auth=vi.fn();const w=new CreateTaskWorkflow({authenticate:auth,token:vi.fn()},f.store,f.authority,()=>{throw new Error('must not run');});await expect(w.preview(bearer,input,'default_off')).rejects.toMatchObject({type:'UNSUPPORTED_CAPABILITY'});expect(auth).not.toHaveBeenCalled();expect(transport).not.toHaveBeenCalled();});
});
