import { describe, expect, it } from 'vitest';
import { randomBytes } from 'node:crypto';
import { MockFeishuAdapter } from '../packages/feishu/src/adapter.js';
import { demoIdentity, demoWorkspaces } from '../packages/feishu/src/fixtures.js';
import { Handles } from '../packages/policy/src/core.js';
import { inputSchemas, outputSchema, readToolNames, toolTraceability, writeToolNames } from '../packages/schemas/src/catalog.js';
import { ToolEngine } from '../packages/tools/src/engine.js';
import type { AuditEvent } from '../packages/observability/src/audit.js';

const range = { start: '2026-10-06T08:00:00Z', end: '2026-10-06T12:00:00Z' };
const timezone = 'Asia/Shanghai';
function setup() { const audit: AuditEvent[] = []; const engine = new ToolEngine(new MockFeishuAdapter(demoWorkspaces()), new Handles(randomBytes(32)), event => audit.push(event)); return { engine, audit, identity: demoIdentity() }; }
const samples: Record<string, Record<string, unknown>> = {
  get_profile: {}, search: { query: 'payment' }, search_people: { query: 'Alex' }, list_chats: {}, search_messages: { query: 'payment' }, get_message_thread: { message_id: 'message-1' }, list_doc_comments: { doc_id: 'doc-1' }, list_bases: {}, get_base_schema: { base_id: 'base-1' }, query_base_records: { base_id: 'base-1', table_id: 'table-1' }, get_agenda: { time_range: range, timezone }, get_free_busy: { time_range: range, timezone, people: ['person-1', 'person-2'] }, suggest_meeting_times: { time_range: range, timezone, people: ['person-2'], duration_minutes: 30 }, list_meeting_rooms: {}, list_tasks: {}, get_task: { task_id: 'task-1' },
};
async function reference(engine: ToolEngine, query = 'Payment', type = 'doc') {
  const result = await engine.call('search', { query, types: [type] }, demoIdentity());
  return ((result.data!.results as { result_id: string }[])[0]!).result_id;
}
describe('read tool contracts', () => {
  it.each(Object.entries(samples))('%s returns a validated synthetic envelope', async (name, input) => { const s = setup(); const result = await s.engine.call(name, input, s.identity); expect(result.ok).toBe(true); expect(outputSchema.safeParse(result).success).toBe(true); expect(result.meta.source).toBe('synthetic_mock'); expect(s.audit).toHaveLength(1); });
  it('fetch returns a paginated source with a stable continuation', async () => { const s = setup(); const resultId = await reference(s.engine); const first = await s.engine.call('fetch', { result_id: resultId, max_chars: 20 }, s.identity); expect(first.ok).toBe(true); expect(first.data!.truncated).toBe(true); const next = await s.engine.call('fetch', { result_id: resultId, max_chars: 20, cursor: first.meta.next_cursor }, s.identity); expect(next.ok).toBe(true); expect(next.data!.content).not.toBe(first.data!.content); });
  it('tracks all thirty tools and enables seventeen reads only', () => { expect(toolTraceability).toHaveLength(30); expect(new Set(toolTraceability.map(tool => tool.name)).size).toBe(30); expect(readToolNames).toHaveLength(17); expect(writeToolNames).toHaveLength(13); });
  it.each(writeToolNames)('does not expose or execute %s', async name => { const s = setup(); const result = await s.engine.call(name, {}, s.identity); expect(result.error!.type).toBe('UNSUPPORTED_CAPABILITY'); });
  it('treats inherited object properties as unknown tools', async () => { const s = setup(); expect((await s.engine.call('toString', {}, s.identity)).error!.type).toBe('UNSUPPORTED_CAPABILITY'); });
  it('rejects unknown arguments rather than changing scope', async () => { const s = setup(); const result = await s.engine.call('get_profile', { tenant_id: 'demo-tenant-two' }, s.identity); expect(result.error!.type).toBe('INVALID_ARGUMENT'); });
  it('enforces the required scope for every registered read', async () => { const s = setup(); for (const [name, input] of Object.entries(samples)) { const result = await s.engine.call(name, input, { ...s.identity, scopes: [] }); expect(result.error!.type).toBe('INSUFFICIENT_SCOPE'); } });
  it('omits unauthorized search domains and marks the result partial', async () => { const s = setup(); const result = await s.engine.call('search', { query: 'Payment' }, { ...s.identity, scopes: ['search.read', 'docs.read'] }); expect(result.ok).toBe(true); expect(result.meta.partial).toBe(true); expect((result.data!.results as { type: string }[]).every(result => result.type === 'doc')).toBe(true); });
  it('requires a domain permission even with search permission', async () => { const s = setup(); const result = await s.engine.call('search', { query: 'Payment' }, { ...s.identity, scopes: ['search.read'] }); expect(result.error!.type).toBe('INSUFFICIENT_SCOPE'); });
  it('rechecks domain scope on fetch', async () => { const s = setup(); const resultId = await reference(s.engine); const result = await s.engine.call('fetch', { result_id: resultId }, { ...s.identity, scopes: ['search.read'] }); expect(result.error!.type).toBe('INSUFFICIENT_SCOPE'); });
  it('blocks same-tenant different-user and cross-tenant handle replay', async () => { const s = setup(); const resultId = await reference(s.engine); for (const account of ['beta', 'gamma']) { const result = await s.engine.call('fetch', { result_id: resultId }, demoIdentity(account)); expect(result.error!.type).toBe('PERMISSION_DENIED'); } });
  it('blocks a forged context before reading synthetic data', async () => { const s = setup(); const result = await s.engine.call('get_profile', {}, { ...s.identity, subject: 'other-user' }); expect(result.error!.type).toBe('PERMISSION_DENIED'); });
  it('does not support arbitrary URL fetching', async () => { const s = setup(); const result = await s.engine.call('fetch', { result_id: 'http://169.254.169.254/metadata' }, s.identity); expect(result.error!.type).toBe('INVALID_ARGUMENT'); });
  it('paginates without duplicates and refuses a changed query', async () => { const s = setup(); const first = await s.engine.call('list_chats', { page_size: 1 }, s.identity); const next = await s.engine.call('list_chats', { page_size: 1, cursor: first.meta.next_cursor }, s.identity); expect(first.data!.chats).not.toEqual(next.data!.chats); expect(next.meta.next_cursor).toBeNull(); const changed = await s.engine.call('list_chats', { query: 'Product', page_size: 1, cursor: first.meta.next_cursor }, s.identity); expect(changed.error!.type).toBe('INVALID_ARGUMENT'); });
  it('returns ambiguous recipient candidates without picking one', async () => { const s = setup(); const result = await s.engine.call('search_people', { query: 'Alex' }, s.identity); expect(result.data!.ambiguous).toBe(true); expect(result.data!.people).toHaveLength(2); });
  it('validates Base field IDs and filter types', async () => { const s = setup(); for (const filter of [{ field_id: 'invented', operator: 'eq', value: 'P0' }, { field_id: 'estimate', operator: 'gt', value: '5' }, { field_id: 'priority', operator: 'gt', value: 'P0' }]) { const result = await s.engine.call('query_base_records', { base_id: 'base-1', table_id: 'table-1', filter }, s.identity); expect(result.error!.type).toBe('INVALID_ARGUMENT'); } });
  it('filters, sorts and projects Base records using existing schema IDs', async () => { const s = setup(); const result = await s.engine.call('query_base_records', { base_id: 'base-1', table_id: 'table-1', filter: { field_id: 'estimate', operator: 'gt', value: 2 }, sort: { field_id: 'estimate', direction: 'desc' }, fields: ['estimate'], page_size: 1 }, s.identity); expect(result.data!.records).toEqual([{ record_id: 'record-2', fields: { estimate: 5 }, updated_at: '2026-10-04T12:00:00Z' }]); });
  it('converts agenda labels to the explicit timezone without changing instants', async () => { const s = setup(); const result = await s.engine.call('get_agenda', { time_range: range, timezone }, s.identity); const event = (result.data!.events as { start: string; local_start: string }[])[0]!; expect(event.start).toBe('2026-10-06T09:00:00Z'); expect(event.local_start).toContain('17:00'); });
  it('does not produce meeting slots overlapping busy events', async () => { const s = setup(); const result = await s.engine.call('suggest_meeting_times', { time_range: range, timezone, people: ['person-2'], duration_minutes: 60, limit: 5 }, s.identity); const slots = result.data!.slots as { start: string; end: string }[]; for (const slot of slots) { expect(Date.parse(slot.end) <= Date.parse('2026-10-06T09:00:00Z') || (Date.parse(slot.start) >= Date.parse('2026-10-06T10:00:00Z') && Date.parse(slot.end) <= Date.parse('2026-10-06T11:00:00Z'))).toBe(true); } });
  it('rejects unknown people instead of assuming their calendar is free', async () => { const s = setup(); const result = await s.engine.call('get_free_busy', { time_range: range, timezone, people: ['unknown-person'] }, s.identity); expect(result.error!.type).toBe('NOT_FOUND'); });
  it('rejects invalid or unbounded temporal inputs', () => { for (const input of [{ time_range: range, timezone: 'invalid/zone' }, { time_range: { start: range.end, end: range.start }, timezone }, { time_range: { start: '2026-01-01T00:00:00', end: range.end }, timezone }]) expect(inputSchemas.get_agenda.safeParse(input).success).toBe(false); });
  it('returns malicious source text as labelled data and never invokes writes', async () => { const s = setup(); const resultId = await reference(s.engine, 'Untrusted', 'file'); const result = await s.engine.call('fetch', { result_id: resultId }, s.identity); expect(result.data!.content_trust).toBe('untrusted_source_data'); expect(result.data!.content).toContain('attacker.example'); expect(s.audit.every(event => ['search', 'fetch'].includes(event.tool))).toBe(true); });
  it('does not log source text, tokens, arguments or raw identities', async () => { const s = setup(); await s.engine.call('search_messages', { query: 'payment' }, s.identity); const log = JSON.stringify(s.audit); for (const banned of ['Payment retry', 'demo-user-alpha', 'demo-connection-alpha', 'access_token', 'refresh_token', 'arguments']) expect(log).not.toContain(banned); expect(Object.keys(s.audit[0]!).sort()).toEqual(['connectionHash', 'durationMs', 'requestId', 'status', 'tool'].sort()); });
});
