import {describe,it,expect,vi} from 'vitest';
import {randomBytes}from'node:crypto';
import {createSafeSdkClient}from'../packages/feishu/src/sdk-client.js';
import {bindSdkReads,FeishuSdkReadGateway}from'../packages/feishu/src/sdk-reads.js';
import {FeishuProviderReads}from'../packages/feishu/src/provider-reads.js';
import {FeishuProviderDomains}from'../packages/feishu/src/provider-domains.js';
import {FeishuProviderWorkflows}from'../packages/feishu/src/provider-workflows.js';
import {demoIdentity}from'../packages/feishu/src/fixtures.js';
import {Handles}from'../packages/policy/src/core.js';
function setup(){const request=vi.fn();const identity=demoIdentity();const handles=new Handles(randomBytes(32));const sdk=createSafeSdkClient({appId:'fixture',appSecret:'fixture',domain:'feishu',httpInstance:{request}as never});const gateway=new FeishuSdkReadGateway({identity,reads:bindSdkReads(sdk)},{get:async()=>({accessToken:'synthetic',refreshToken:'synthetic',expiresAt:Date.now()+1e6,refreshExpiresAt:Date.now()+2e6})});const reads=new FeishuProviderReads(gateway,handles);const domains=new FeishuProviderDomains(gateway,handles);return {request,identity,handles,workflows:new FeishuProviderWorkflows(reads,domains,gateway,handles)}}
const doc=(id:string,hasMore=false,token?:string)=>({code:0,data:{has_more:hasMore,...(token?{page_token:token}:{}),res_units:[{entity_type:'DOC',title_highlighted:id,result_meta:{token:id,doc_types:'DOCX'}}]}});
const msg=()=>({code:0,data:{has_more:false,items:[{meta_data:{message_id:'msg_fixture'},display_info:'Message'}]}});
describe('independent workflow edge cases',()=>{
 it('advances a two-page document domain then reaches messages with no dropped page',async()=>{const s=setup();s.request.mockResolvedValueOnce(doc('doc1',true,'upstream2')).mockResolvedValueOnce(doc('doc2')).mockResolvedValueOnce(msg());const types:string[]=[];let cursor:string|undefined;for(let i=0;i<3;i++){const page=await s.workflows.search(s.identity,{query:'fixture',cursor});types.push(...page.results.map(r=>r.title));cursor=page.next_cursor??undefined;}expect(types).toEqual(['doc1','doc2','Message']);expect(cursor).toBeUndefined();expect(s.request.mock.calls[1]![0].data.page_token).toBe('upstream2');expect(s.request.mock.calls[2]![0].params.page_token).toBeUndefined()});
 it('stops repeating a provider page token instead of issuing endless same-domain continuations',async()=>{const s=setup();s.request.mockResolvedValue(doc('doc1',true,'repeating'));const page=await s.workflows.search(s.identity,{query:'fixture'});await expect(s.workflows.search(s.identity,{query:'fixture',cursor:page.next_cursor!})).rejects.toThrow();});
 it('does not claim nested comments complete when the reply array is missing',async()=>{const s=setup();s.request.mockResolvedValue({code:0,data:{has_more:false,items:[{comment_id:'c1',has_more:false,reply_list:{}}]}});const result=await s.workflows.comments(s.identity,'doc1');expect(result.partial).toBe(true);expect(result.comments[0]!.replies_complete).toBe(false)});
 it('rejects permission loss before fetching either a wiki node or a document',async()=>{const s=setup();const ref=s.handles.encode('resource',s.identity,{provider:'feishu',kind:'wiki',id:'wiki1'});await expect(s.workflows.fetch({...s.identity,scopes:['search.read']},{result_id:ref})).rejects.toThrow('permission');expect(s.request).not.toHaveBeenCalled()});
 it('rejects an altered signed fetch handle without a provider request',async()=>{const s=setup();const ref=s.handles.encode('resource',s.identity,{provider:'feishu',kind:'doc',id:'doc1'});await expect(s.workflows.fetch(s.identity,{result_id:ref+'x'})).rejects.toThrow();expect(s.request).not.toHaveBeenCalled()});
 it('skips a filtered-out final docs page and reaches messages',async()=>{const s=setup();s.request.mockResolvedValueOnce(doc('doc1')).mockResolvedValueOnce(msg());const result=await s.workflows.search(s.identity,{query:'fixture',types:['wiki','message']});expect(result.results.map(r=>r.type)).toEqual(['message']);expect(result.next_cursor).toBeNull()});
 it('rejects a reply from another chat even if its thread_id matches',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{message_id:'m1',chat_id:'chat1',thread_id:'thread1'}]}}).mockResolvedValueOnce({code:0,data:{has_more:false,items:[{message_id:'m2',chat_id:'chat2',thread_id:'thread1'}]}});await expect(s.workflows.messageThread(s.identity,'m1')).rejects.toThrow('outside')});
 it('rejects a continuation if the authoritative thread changed since page one',async()=>{const s=setup();s.request.mockResolvedValueOnce({code:0,data:{items:[{message_id:'m1',chat_id:'chat1',thread_id:'thread1'}]}}).mockResolvedValueOnce({code:0,data:{has_more:true,page_token:'page2',items:[{message_id:'m2',chat_id:'chat1',thread_id:'thread1',msg_type:'text',body:{content:'{"text":"reply"}'}}]}}).mockResolvedValueOnce({code:0,data:{items:[{message_id:'m1',chat_id:'chat1',thread_id:'thread2'}]}});const first=await s.workflows.messageThread(s.identity,'m1');await expect(s.workflows.messageThread(s.identity,'m1',{cursor:first.next_cursor!})).rejects.toThrow('another');expect(s.request).toHaveBeenCalledTimes(3)});
});
